### ISSUE TITLE
Connection to database problem

### ISSUE THREAD

**Issue by medahmedey** [francoisjacquet/rosariosis#1]
I had a problem connecting to my postgresql database (which i named 'rosariosis') from the 'database.inc.php' file. In this file the function db_start() contains the following lines:

global $DatabaseServer,$DatabaseUsername,$DatabasePassword,$DatabaseName,$DatabasePort;

```
$connectstring = '';
if($DatabaseServer!='localhost')
    $connectstring = "host=$DatabaseServer ";
if($DatabasePort!='5432')
    $connectstring .= "port=$DatabasePort ";
$connectstring .= "dbname=$DatabaseName user=$DatabaseUsername";
if(!empty($DatabasePassword))
    $connectstring.=" password=$DatabasePassword";
$connection = pg_connect($connectstring);
```

Actually I didn't understand exactly waht the  tests 

if($DatabaseServer!='localhost')
    $connectstring = "host=$DatabaseServer ";
if($DatabasePort!='5432')
    $connectstring .= "port=$DatabasePort ";

are supposed to bring. 

I just commented them and it worked. 

In fact with those tests you can't connect to the database from your localhost or with the default port 5432.

Thanks a lot for your work in this project. Respects

PS: Excuse my english.

**Comment by dannapel** [comment]
hi francois, i have the same exact problem, i followed all the instructions here but nothing worked. so i checked my apache error log and i got this:
[Wed Aug 12 14:47:52.478201 2015] [:error] [pid 507] [client 41.220.68.241:32443] PHP Fatal error:  Cannot redeclare SendEmail() (previously declared in /home/Public_html/rosario/ProgramFunctions/SendEmail.fnc.php:29) in /home/Public_html/rosario/ProgramFunctions/SendEmail.fnc.php on line 29

Does sendmail function really prevent the program from running? PLease i need your help with this.
I have ubuntu 14.04 with php 5.5.9 and apache 2.4.7..postgresql is 9.3.9
