### ISSUE TITLE
Session Not Working. Can't find out why!

### ISSUE THREAD

**Issue by marciozero** [francoisjacquet/rosariosis#101]
Hello Francois,

first of all, let me contratulate you for the AWESOME solution you have shared with all of us.

Now, the thing is: I'm using MacOs, with PostgreSQL, Apache and MAMP. I just installed the git pack, and all seemed to be working fine at first.

But the thing is: I log in as admin, I can see the main window of the system, but everytime I click one of the options, the system log me out!

Using MacGDBp to debug the code, I found out that when I reach this part of the code:

	if(!$_SESSION['STAFF_ID'] && !$_SESSION['STUDENT_ID'] && basename($_SERVER['SCRIPT_NAME'])!=='index.php')
	{
?>
		<script>window.location.href = "index.php?modfunc=logout";</script>
<?php
		exit;
	}

The system enters this "IF" and then exits.

Can you help me?

Thanks in advance!

**Comment by francoisjacquet** [comment]
Which version of RosarioSIS are you using? Have you tried updating to 2.8.5?
You should also check the diagnostic.php page.
Please tell me if it fixed your issue.

**Comment by marciozero** [comment]
Aparently, it have something to do with my apache server, because I used the same code in my windows machine and it all worked fine!

**Comment by francoisjacquet** [comment]
Alright so it should caused by your PHP configuration then.

Have you followed the instructions mentioned in my previous message?

By the way, you could contribute with a installation tutorial for Mac.

**Comment by durich** [comment]
I had this issue in an installation of rosariosis v2.8.6 in my linux desktop.

I had to change the session.auto_start from 0 to 1 in the php.ini file so I could make logged in.

**Comment by francoisjacquet** [comment]
There must be a problem with the [_session_regenerate_id_](http://php.net/manual/en/function.session-regenerate-id.php) function, but I cannot find what exactly as I never could reproduce the issue on 2 different servers (#96).

**Comment by durich** [comment]
Hi,

To help you reproduce the problem, I can send you my /etc/php5 configuration from my ubuntu server.

The linux installed in this server is a Ubuntu 14.04 with php version 5.5.9-1ubuntu4.7 and Apache Apache/2.4.7

It is really strange because I have the exact code running on a windows machine and it works fine with the parameter session.auto_start  set to 0.

**Comment by francoisjacquet** [comment]
I was able to reproduce the problem messing with the [session cookie path](https://github.com/francoisjacquet/rosariosis/commit/c1efea8eeac0c3575cc167c9caaec69b72861a0f). Could you please give me feedback on this fix and tell me if the problem still persists with _session.auto_start_ set to 1?

**Comment by durich** [comment]
The new patch seems to fix the logging problem in my linux desktop with  session.auto_start set to 0 or 1.

**Comment by francoisjacquet** [comment]
Thank you for your help.
Issue closed
