### ISSUE TITLE
I get this error after importing sql data

### ISSUE THREAD

**Issue by ronelgon** [francoisjacquet/rosariosis#102]
After importing sql data i see this below
SET
SET
SET
rosariosis.sql:28: ERROR: language "plpgsql" does not exist
HINT: Use CREATE LANGUAGE to load the language into the database.
rosariosis.sql:50: ERROR: language "plpgsql" does not exist
HINT: Use CREATE LANGUAGE to load the language into the database.
rosariosis.sql:73: ERROR: language "plpgsql" does not exist
HINT: Use CREATE LANGUAGE to load the language into the database.
rosariosis.sql:132: ERROR: language "plpgsql" does not exist
HINT: Use CREATE LANGUAGE to load the language into the database.
rosariosis.sql:169: ERROR: language "plpgsql" does not exist
HINT: Use CREATE LANGUAGE to load the language into the database.
rosariosis.sql:226: ERROR: language "plpgsql" does not exist
HINT: Use CREATE LANGUAGE to load the language into the database.
rosariosis.sql:251: ERROR: language "plpgsql" does not exist
HINT: Use CREATE LANGUAGE to load the language into the database.
SET
SET
CREATE TABLE
CREATE SEQUENCE

setval
1

1 row(s)

CREATE TABLE
CREATE SEQUENCE

setval

What could be the problem?

Your help will be highly appreciated

Thank you
Ronnie

**Comment by francoisjacquet** [comment]
Maybe this could help:

http://stackoverflow.com/questions/2122207/postgresql-language-pgplsql-does-not-exist-despite-running-create-language

http://stackoverflow.com/questions/19376272/etherpad-postgresql-error-language-plpgsql-does-not-exist

Please share your solution once you have fixed the errors.

**Comment by ronelgon** [comment]
Hello,
Kindly help me with steps to create function Language plpgsql

Thank you
Ronnie
