### ISSUE TITLE
I have installed version latest version but have these issues

### ISSUE THREAD

**Issue by ronelgon** [francoisjacquet/rosariosis#103]
Hello,
Thanks for the hardwork.Iam here trying to learn it but after installing the latest version, i get this information from the diagnostic.php page
Errors:

PHP extensions: RosarioSIS relies on the xmlrpc extensions (only used to connect to Moodle). See the php.ini file to activate it. Loaded php.ini: /usr/local/lib/php.ini
The value for $RosarioPath in config.inc.php is not correct or else the functions directory does not have the correct permissions to be read by the webserver. Make sure $RosarioPath points to the RosarioSIS installation directory and that it is readable by all users.
The value for $wkhtmltopdfPath in config.inc.php is not correct.

Qns
1. What is the correct path if the installation is in a sub-domain of my website (e.g http://mydomain.com/rosariosis/) ?
2. How do i correct The value for $wkhtmltopdfPath in config.inc.php or what should i put there?
3. Is there an easy way to activate the xmlrpc extensions without going to the php.ini file in database? because i have no access to it.

Your help will be highly appreciated

Thank you
Ronnie

**Comment by francoisjacquet** [comment]
Please contact me via http://www.rosariosis.org/services/ for installation issues.

Thank you,
François
