### ISSUE TITLE
Default password issue with matching syear

### ISSUE THREAD

**Issue by SessionPod** [francoisjacquet/rosariosis#105]
Hi there,

Hope someone can help me. I have a fresh install running in a hosted environment with Postgres 8.1.23. The first problem I had was a blank screen when I tried to access index.php. I resolved this by granting All Privilages manually to the database owner. Now I can see the login page but I cannot login using the default username and password. Using phpPgAdmin I have altered the default value of databasename\Public\Schools\syear to 2015 (It was blank so I read prom previous threads there should be a default value or else you cannot login. I hope this is ok - I am not a DBA). This is also the value in config.inc.php. But I still can't login....

Can anyone help me!

//SessionPod

**Comment by francoisjacquet** [comment]
Hi,

I will update the rosariosis.sql to 2015 in June.

In the meantime, if you are interested in switching right now to 2015, I 
can help you.
Please contact me at http://www.rosariosis.org/services/

**Comment by SessionPod** [comment]
Hi there,

Many thanks for the reply. My current interest in RosarioSIS is to evaluate functionality and community support.

If my login issue is a simple case of entering a default year in the config.inc.php file then much appreciated if someone can tell me what this value should be.

Installation complete but I still cannot login. Diagnostic tells me "The value for $DefaultSyear in config.inc.php is not correct". Currently the value $DefaultSyear in config.inc.php is set at 2014.

Any help greatly appreciated.

//Rob

**Comment by thesmahesh** [comment]
Dear All,

I have the same issue and am unable to login with admin/admin ; teacher/teacher etc
rosariosis version 2.9.2
diagnostic.php gives the error
Error: The value for $DefaultSyear in the config.inc.php file is incorrect.

verified the syear field of the user matches the DefaultSyear config variable in the config.inc.php file
Both are 2015

Any help on this will be very much appreciated.
Thanks and Regards

**Comment by francoisjacquet** [comment]
Hello @thesmahesh 

You can double check by yourself running the following SQL command against your database:
`SELECT * FROM STAFF WHERE SYEAR='2015';`

Please tell us what it returns.

**Comment by thesmahesh** [comment]
Hello @francoisjacquet 
It returns 3 users

[rosariosis.xlsx](https://github.com/francoisjacquet/rosariosis/files/283487/rosariosis.xlsx)

admin
teacher
parent

Have exported results and have enclosed the csv file
Please help resolve the issue.

**Comment by thesmahesh** [comment]
Hello @francoisjacquet 
My postgres has the given below configuration
local all all md5
I assume that the above is meant as authentication for logging to postgres db as "md5" user password and has nothing to do with your internal password encryption methods.
Please correct me if i am wrong and if there is any change required.
Thanks and Regards

**Comment by francoisjacquet** [comment]
Hello @thesmahesh 

Thank you for posting the SQL request results. Your postgres configuration looks fine too.

We can conclude the error returned by the `diagnostic.php` script indicates you either connect to another database (see the `config.inc.php` file), or there is an error related to this specific SQL request or table.

If you would like us to investigate more into this problem, please contact us at http://rosariosis.org/services

**Comment by thesmahesh** [comment]
Hello @francoisjacquet 

I finally resolved the issue and was able to login by doing the given below:

(My environment: Centos 7 and postgres 9 with phppgadmin.
Those who are running on Windows may kindly identify the paths to the specified files and try my solution and inform whether it works...)

1)Open -> /etc/phppgadmin -> config.inc.php

2)change $conf['extra_login_security'] = true; to $conf['extra_login_security'] = false;

3)
/etc/init.d/httpd restart
and
service postgresql restart

Hope, it will be helpful for someone experiencing the issue.

Thanks and Regards

**Comment by francoisjacquet** [comment]
Great!

Here is the documentation for the `extra_login_security` option:

> If extra login security is true, then logins via phpPgAdmin with no
    password or certain usernames (**pgsql, postgres, root, administrator**)
    will be denied. Only set this false once you have read the FAQ and
    understand how to change PostgreSQL's pg_hba.conf to enable
    passworded local connections.
