### ISSUE TITLE
Trouble with the translation.

### ISSUE THREAD

**Issue by murilotimo** [francoisjacquet/rosariosis#107]
I'm using Windows 8 64-bit with wampp 2.5 32-bit.

The translation is not working, everything works fine, but ... all in English ...

I am Brazilian, a physics teacher at a public school in the suburb.

if I can use the rosariosis, I'll contribute a module to generate a barcode for each student integrated with the attendance system.

help me run the translation system?

What dumb am I doing?

ps: I'll help with the translation into Brazilian Portuguese also, I'm trying to Portuguese of Portugal

**Comment by francoisjacquet** [comment]
Hi,

Wamp is known not to work well with gettext (the translation program).

François

**Comment by francoisjacquet** [comment]
A new [tutorial for Windows](https://github.com/francoisjacquet/rosariosis/wiki/How-to-install-RosarioSIS-on-Windows) is available.
The translations have been successfully tested!

Cheers
