### ISSUE TITLE
ERROR Cant create database 

### ISSUE THREAD

**Issue by 66koko** [francoisjacquet/rosariosis#108]
When copy pasting rosariosis sql script, I am getting this error. 
SQL error:

ERROR:  syntax error at or near "="
LINE 5: SET client_encoding = 'UTF8';

 I still can create the db if attach the sql script.
@francoisjacquet Help

**Comment by francoisjacquet** [comment]
Simply uncheck "Paginate Results" in phpPgAdmin.

**Comment by 66koko** [comment]
Thanks.
