### ISSUE TITLE
Setting up State Reporting

### ISSUE THREAD

**Issue by johnrivers1979** [francoisjacquet/rosariosis#11]
I would like to know how I can set up the State Reporting module. I unzipped the actual module and loaded its SQL file. But when I open it, it gives me a blank screen on he right frame and nothing works. What do I need to do to get this working right?

**Comment by francoisjacquet** [comment]
I am pleased to announce the **Reports module** has been adapted for RosarioSIS and is available for download: https://github.com/francoisjacquet/rosariosis-module-reports
