### ISSUE TITLE
Moodle integrator: error message from Moodle when trying to add a new subject

### ISSUE THREAD

**Issue by myii** [francoisjacquet/rosariosis#110]
RosarioSIS version: 2.8.16
Moodle version: 2.9

diagnostic.php:
Your RosarioSIS installation is properly configured.

Have followed instructions @ https://github.com/francoisjacquet/rosariosis/wiki/Moodle-integrator-setup.  Let me be clear: nothing is being updated Moodle-side (have tried adding students, parents and teachers).  However, the only Rosario-side feedback I have got is the following error (happens every time a new subject is added):

> Error: Moodle: 32877907 - The web service description parameter named 'userid' is an single or multiple structure. It can not be set as VALUE_OPTIONAL. Check web service description. | ERRORCODE: erroroptionalparamarray

Before I set debug mode, the error was simply:
> Error: Moodle: 404 - Unknown error

Any idea what this could be?

**Comment by francoisjacquet** [comment]
Hello @myii

RosarioSIS Moodle integrator has not been tested with Moodle 2.9 yet.
An unprobable change in webservices between Moodle 2.8 and Moodle 2.9 
may be the problem.

Please carefully revise the steps in the Wiki article.

**Comment by myii** [comment]
@francoisjacquet Thanks for your reply.  We're just evaluating different open-source offerings.  It took me about half an hour to go through those steps so I'll wait until RosarioSIS has been tested with 2.9.  In the meantime, just as a comparison for you, the following open-source product only takes 5 minutes to configure Moodle and easy to test during the process of configuration:
https://gibbonedu.org/support/administrators/connecting-to-moodle/

Perhaps RosarioSIS can consider using an external database method in a similar fashion.  In any case, we definitely been impressed with RosarioSIS so kudos to you for all of your efforts!

**Comment by myii** [comment]
@francoisjacquet By the way, while I've got my installations available, I can try to make time to do any tests for you using my environment.  I've followed the steps meticulously and there is some obvious communication between RosarioSIS and Moodle - as can be seen by the error message.

**Comment by francoisjacquet** [comment]
I confirm the issue.

The issue have been reported on Moodle's webservices forum (please read to know more):
https://moodle.org/mod/forum/view.php?f=965
Wait and see...

**Comment by myii** [comment]
Thanks for that.  Look forward to a resolution.

**Comment by francoisjacquet** [comment]
The bug have been reported on Moodle tracker too:

https://tracker.moodle.org/browse/MDL-50759

**Comment by francoisjacquet** [comment]
The bug has been fixed in Moodle 2.9.2+, please refer to https://tracker.moodle.org/browse/MDL-50759

**Comment by myii** [comment]
Thanks for your help.
