### ISSUE TITLE
Syntax error while installing Rosario in Windows

### ISSUE THREAD

**Issue by diimaan** [francoisjacquet/rosariosis#113]
I am installing Rosario in Windows. I have followed the tutorial from here https://github.com/francoisjacquet/rosariosis/wiki/How-to-install-RosarioSIS-on-Windows

In step 10 I copy pasted the SQL from rosariosis.sql file.

When I click execute it throws a syntax error on the very first line. 

ERROR:  syntax error at or near "="
LINE 5: SET client_encoding = 'UTF8';

I removed that line, then it showed the same error on next line

ERROR:  syntax error at or near "="
SET check_function_bodies = false;

Please correct me if I am doing anything wrong! Thanks

**Comment by francoisjacquet** [comment]
@diimaan, please uncheck "Paginate results" before executing the SQL in 
phpPgAdmin.

The step 10 of the tutorial has been consequently updated.

**Comment by diimaan** [comment]
Thanks for the suggestion. I will do that and let you know how did it go!
