### ISSUE TITLE
About languages

### ISSUE THREAD

**Issue by samleneveu** [francoisjacquet/rosariosis#116]
Hello support,
how can i change language on rosariosis 2.8, when i click on language icon on login screen, title and value of Locale change but no text also when i'm in system.There are capture screen.
In this example i select french for language
![screen1](https://cloud.githubusercontent.com/assets/14165008/9719833/33c4b464-5580-11e5-900c-59c5bbea7c68.png)
![screen2](https://cloud.githubusercontent.com/assets/14165008/9719834/33f660ae-5580-11e5-93a1-5695fa0a30f7.png)

**Comment by francoisjacquet** [comment]
Hello @samleneveu 

If you have followed the tutorial to install RosarioSIS on Windows, you may experience issues with gettext and WAMP Server.

If not, wether you are using EasyPHP, or Bitnami WAPP stack, please activate the _gettext_ PHP extension to have translations working.

**Comment by samleneveu** [comment]
i checked gettext extension is active, problem isn't solve

**Comment by francoisjacquet** [comment]
A new [tutorial for Windows](https://github.com/francoisjacquet/rosariosis/wiki/How-to-install-RosarioSIS-on-Windows) is available.
The translations have been successfully tested!

Cheers

**Comment by francoisjacquet** [comment]
The tutorial now recommends WAPP stack version 7.1.
Translations work **without** `gettext` on Windows.
