### ISSUE TITLE
Permission error when trying to added Student Fields

### ISSUE THREAD

**Issue by cgaitwood** [francoisjacquet/rosariosis#118]
I am trying to add an email field to the student fields under general info I get the error below.  I have added all of the permissions for the my database user that I can in phpPgAdmin.  I am under a shared hosting account so I can not modify permissions under the public schema under my database.  All other functions within the RosarioSIS application are working as expected.  I have installed version 2.8.23 of RosarioSIS.  Any assistance would be appreciated.

Date:10/28/2015 09:30:33
Failure Notice:	 DB Execute Failed. 
Additional Information:	ERROR: must be owner of relation students

**Comment by francoisjacquet** [comment]
@cgaitwood as the error states, your PostgreSQL user is not the owner of the `STUDENTS` table.

The _rosariosis.sql_ file should be imported with the same user you use to connect.
If your shared hosting does not allow that, then you will not be able to use RosarioSIS properly.

**Comment by cgaitwood** [comment]
Thanks for getting back to me.  I will check with the hosting vendor.
