### ISSUE TITLE
Student Emails

### ISSUE THREAD

**Issue by cgaitwood** [francoisjacquet/rosariosis#119]
We would like to be able to text and email students messages from RosarioSIS.  Is this in the enhancements timeline for the product?

**Comment by francoisjacquet** [comment]
Hello @cgaitwood,

A new additional module for RosarioSIS is currently in development. It will add the following features:
- Email Discipline Reports to Parents
- Email Student Balances to Parents
- Email Report Cards to Parents

The Email Students feature can be added to this module.
Please contact us at http://www.rosariosis.org/services/ if you are interested.

**Comment by francoisjacquet** [comment]
You can now email students (and users) from RosarioSIS using the [Email module](https://www.rosariosis.org/email-module/).
