### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by olameen** [francoisjacquet/rosariosis#12]
Hi Francois,
After 3 days of banging my head, I now need your assistance.
I am using WAPP 5.4.23, PostgreSQL 9.3.1 running on localhost:5432 with PHP Version 5.4.23. running on win 7 64
Imported the sql file successfully ( all tables/views etc  have been created ) in a database named rosariosis and filled out config.inc accordingly but I have a blank page when i load the app in the browser. Page source is blank as well. I really dont know what is wrong.
Any help will be appreciated

**Comment by 123nikhitha** [comment]
Hi,
I am using WAPP 5.4.23, PostgreSQL 9.3.1 running on localhost:5432 with PHP Version 5.4.23. running on win 7 64
Imported the sql file successfully ( all tables/views etc have been created ) in a database named rosariosis and filled out config.inc accordingly but I have a blank page when i load the app in the browser. Page source is blank as well. I really dont know what is wrong.
Any help will be appreciated

**Comment by 123nikhitha** [comment]
please reply me fast

**Comment by tuntoy** [comment]
As for me i am running it on window 7 but there are 2 php.ini is it php.ini-development or php.ini-production though i remove the semi colom from both but the last result i get is Error: PHP extensions: RosarioSIS relies on the gettext extension. Please install and activate it. so how do i activated it

**Comment by francoisjacquet** [comment]
Hello @tuntoy

To activate the PHP `gettext` extension on Windows, please follow the instructions available in the tutorial: https://github.com/francoisjacquet/rosariosis/wiki/How-to-install-RosarioSIS-on-Windows#activate-the-php-gettext-extension

This should work if you have the _right_ WAPP stack already installed.
