### ISSUE TITLE
 guide for installing rosariosis on  linux hosting, Cpanel with postgresql and phppgadmin

### ISSUE THREAD

**Issue by jeetdebnath** [francoisjacquet/rosariosis#121]
Please kindly guide for installing rosariosis on  linux hosting, Cpanel with postgresql and phppgadmin. 

After trying installing there is an error showing-

Fatal error: Call to undefined function pg_escape_string() in /database.inc.php on line 258

**Comment by francoisjacquet** [comment]
Hello @jeetdebnath 
There is no specific tutorial for cPanel.
Some users have reported the impossibility to install RosarioSIS on cPanel, especially when ssh access to the server is not available.

Your specific error indicates the PostgreSQL extension for PHP is not installed on your server.
If you need more support, please contact us at http://www.rosariosis.org/services
