### ISSUE TITLE
Danish translation

### ISSUE THREAD

**Issue by dagofacom** [francoisjacquet/rosariosis#122]
Hi, I would like to handle the danish translation. :)

**Comment by francoisjacquet** [comment]
Hello @dagofacom ,

You are welcome!

To start a new translation, you can follow the instructions available in the Wiki: https://github.com/francoisjacquet/rosariosis/wiki/Localizing,-translate-RosarioSIS-with-Poedit

The locale name should be _da_DK.utf8_

**Comment by francoisjacquet** [comment]
Hi @dagofacom , hoping this does not come in too late:

Please find a Danish translation for 38% of RosarioSIS strings: 
[da_DK.utf8.zip](https://github.com/francoisjacquet/rosariosis/files/76439/da_DK.utf8.zip)

Do not forget to update the catalog base source path within Poedit.

Cheers

**Comment by francoisjacquet** [comment]
Hello @dagofacom did you manage to translate RosarioSIS to Danish? Please share any progress you made with us :)
