### ISSUE TITLE
Significance of syear in rosariosis

### ISSUE THREAD

**Issue by affiezaladnan** [francoisjacquet/rosariosis#123]
Hi,

What is the significance of syear in rosariosis, since there is a lot of references of it, especially in the database table.

Also can you explain the concept behind migration and how it ties in with syear.

Thanks.

**Comment by francoisjacquet** [comment]
Hello @affiezaladnan 

`syear` means **School Year**. To change the School Year, you must use the _Rollover_ program first to roll data to the next School Year.

Regarding students, addresses, and parents imports / database migration, you can head to this [wiki page](https://github.com/francoisjacquet/rosariosis/wiki/Import-students,-parents-and-addresses-into-RosarioSIS).
We also plan to develop a generic CSV import module for RosarioSIS.

**Comment by affiezaladnan** [comment]
I am doing the migration via sql directly to postgresql. I am worried that when i see a lot of tables has syear field. Does this mean that i have to duplicate data in staff table every year?

Also, I am populating data for 2016 now but how do i test whether the data is corectly entered, since now is not yet 2015. Thanks
