### ISSUE TITLE
ID number changing for users when rollover is applied

### ISSUE THREAD

**Issue by affiezaladnan** [francoisjacquet/rosariosis#124]
Hi,

I've noticed that the ID number for users will change whenever a rollover is performed. Is this why the database table 'staff' has a column called rollover_id? Is there a way to have users (especially teacher) to have a fixed ID number so that it can be used as a real-life ID number (like social security number etc)

Thanks.

**Comment by francoisjacquet** [comment]
@affiezaladnan as mentioned in #123 please use the **Rollover** program. This will give you a good idea of how data is rolled in the database.
