### ISSUE TITLE
Volunteer for RosarioSIS Translation for Bahasa Melayu (Malaysia)

### ISSUE THREAD

**Issue by affiezaladnan** [francoisjacquet/rosariosis#125]
Hi,

I would like to translate rosariosis to my language
id: ms_MY
Name: Malay (Malaysia)
Local Name: Bahasa Melayu (Malaysia)

Thanks.

**Comment by francoisjacquet** [comment]
Hello @affiezaladnan ,

You're very much welcome!

To start a new translation, you can follow the instructions available in the Wiki: https://github.com/francoisjacquet/rosariosis/wiki/Localizing,-translate-RosarioSIS-with-Poedit

Please note that some English abbreviations are in use within RosarioSIS (for example: "MP" for Marking Periods).

**Comment by francoisjacquet** [comment]
Please find a Malaysian translation for 38% of RosarioSIS strings [ms_MY.utf8.zip](https://github.com/francoisjacquet/rosariosis/files/76432/ms_MY.utf8.zip)

Do not forget to change the _catalog source path_ within Poedit.

**Comment by francoisjacquet** [comment]
Hello @affiezaladnan  did you manage to translate RosarioSIS to Malasyan? Please share any progress you made with us :)
