### ISSUE TITLE
Mass assign fees not accepting negative values

### ISSUE THREAD

**Issue by affiezaladnan** [francoisjacquet/rosariosis#126]
Hi Francois,

The student mass assign fee cannot accept negative values and store those numbers as positive value.

The problem could be the regular expression used
original 
[^0-9,.]+

should be 
[^-+0-9,.]+

So far I've tested this and it is OK. Can you confirm?

**Comment by francoisjacquet** [comment]
Hello @affiezaladnan 

Thank you for reporting the issue, the fixes will be available in the next release.
