### ISSUE TITLE
Rollover problems

### ISSUE THREAD

**Issue by lrcarlisle** [francoisjacquet/rosariosis#127]
When we rolled over all the information from the previous school year, we noticed that not all the students were rolled over.  Some were, some weren't.

**Comment by francoisjacquet** [comment]
The Rollover program rolls students over to the next school year based on:
 1. Rolling / Retention options (see _Students > Student Info > General Info_ tab)
 2. Next Grade (see _School Setup > Grade Levels > Next Grade_ column)

If you still experience problems after configuring RosarioSIS, please contact us directly for support at https://www.rosariosis.org/services/
