### ISSUE TITLE
Changing Student ID from numeric value to alphanumeric value

### ISSUE THREAD

**Issue by dpredster** [francoisjacquet/rosariosis#128]
Hi,

Would it be possible to change the Student ID from numeric value to alphanumeric value and what would be required? 

I have looked into changing all student_id type from numeric to character varying in the database however it causes some problems for example Group by Family trows a database error.

Any help would be appreciated. Also thank you for this great software.

**Comment by francoisjacquet** [comment]
Hi @dpredster ,

It is not possible to change the _Student ID_ to an alphanumeric field.

If you want to record alphanumeric values, please use the _Username_ field or create a new _Student Field_.

**Comment by dpredster** [comment]
Hi,

Thanks for the prompt reply. I will do that.

One more thing. How do you set the email to address for hacking log in the sendEmail function. I would like the program to send an email when there is an sql error of hacking event.

Thanks

**Comment by francoisjacquet** [comment]
Hi @dpredster ,

We can offer you email support for the use and configuration of RosarioSIS at https://www.rosariosis.org/services/
