### ISSUE TITLE
Could not Connect to Database Server

### ISSUE THREAD

**Issue by iniekot** [francoisjacquet/rosariosis#130]
please i am trying to install rosariosis on ubuntu 14.04, i have install postgresql and everything seems to me okay with the server but i am have the following error when i try to install rosariosis;
--
We have a problem, please contact technical support ...

Date:	
02/29/2016 02:38:24
Failure Notice:	
 Could not Connect to Database Server '*' 
Additional Information:	
--
please i will really appreciate any help on this.

**Comment by francoisjacquet** [comment]
@iniekot The error message you have provided indicates RosarioSIS cannot connect to the * database server.
Please review your database configuration in the `config.inc.php` file.

Please contact us at https://www.rosariosis.org/services/ if you need help regarding installation problems.

**Comment by muse-sisay** [comment]
For anyone looking for a solution refer to my https://github.com/francoisjacquet/rosariosis/issues/220#issuecomment-940214256
