### ISSUE TITLE
When I click "School Setup.Database backup" will RosarioSIS create a new backup copy or will RosarioSIS restore the last backup?

### ISSUE THREAD

**Issue by cursogalileu** [francoisjacquet/rosariosis#132]
"Download Backup File" seems me like "Restore Backup File".

**Comment by danfelbm** [comment]
It will create a copy of the Database for you to download

**Comment by francoisjacquet** [comment]
To _download_ a file means get it from the server and save it to your computer.
To _upload_ a file means send it to the server.

FYI, RosarioSIS does not provide a tool to restore a backup.
