### ISSUE TITLE
RosarioSIS "Student Info" have "Attendance Start Date this School Year" and "Dropped". For Attendance Date we have "Codes" and have no "Codes" for Dropped. 

### ISSUE THREAD

**Issue by cursogalileu** [francoisjacquet/rosariosis#133]
How can I create "Drop Codes" Pull Down list?

**Comment by cursogalileu** [comment]
Sorry. I´m learning Rosario SIS. The Drop Code is at same screen than register Attendance Codes.

**Comment by francoisjacquet** [comment]
@cursogalileu we advise you to first follow the [Quick Setup Guide](https://www.rosariosis.org/quick-setup-guide/).
It contains a step about Enrollment codes.

If you need support for RosarioSIS configuration & use, please contact us directly at http://rosariosis.org/services

Thank you,
François

**Comment by cursogalileu** [comment]
Mr. François Jacquet, 

I sent a message via GitHub with a big "Sorry". I read the Quick Setup
Guide. I downloaded Rosario SIS on March/18th, four days past. I´m using
it and I´m very happy. Sometimes something passes like a ghost...
rsrsrsrs... and Drop Codes passed like it... 

Thanks for your patience. Thanks also to "danflbm". 

Cheers, 

 Hugo Penido Gattoni
 BELO HORIZONTE
 MINAS GERAIS
 BRASIL 

Em 2016-03-22 13:44, François Jacquet escreveu: 

> @cursogalileu [1] we advise you to first follow the Quick Setup Guide [2].
> It contains a step about Enrollment codes. 
> 
> If you need support for RosarioSIS configuration & use, please contact us directly at http://rosariosis.org/services [3] 
> 
> Thank you,
> François 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub [4]
 

Links:
------
[1] https://github.com/cursogalileu
[2] https://www.rosariosis.org/quick-setup-guide/
[3] http://rosariosis.org/services
[4]
https://github.com/francoisjacquet/rosariosis/issues/133#issuecomment-199897943

**Comment by danfelbm** [comment]
Anything you need ;)

**Comment by cursogalileu** [comment]
As I promised, here is problem solution to have smartphone accessing Rosario SIS on my PC:
1.- Go to **Start** and type **cmd** on your PC Windows
2.- On "DOS" screen goto to main directory (C:)
3.- type **ipconfig**
4.- Search results to find **IPv4**
5.- In front of IPv4 you could get the **IP** of your PC (something like **192.168.0.01** - not this value!)
6.- type on your SmartPhone: **192.168.0.01/rosariosis/rosariosis-2.8.26/index.php** (remember to change the IP address for the value you found in front of IPv4).
7.- That´s All Folks!

I need to say "Thank you" to François Jacquet and "danflbm"!
Best regards.

**Comment by danfelbm** [comment]
I'm very glad that worked for you!
Don't hesitate to let me know if there is anything else I can help you with...
