### ISSUE TITLE
RosarioSIS have no way to create/show a "Teachers File" with something like name, address, courses, periods avaliable, and so on.

### ISSUE THREAD

**Issue by cursogalileu** [francoisjacquet/rosariosis#134]
Teachers are inserted like "Users". Is this my feeling. Am I correct?

**Comment by danfelbm** [comment]
You are right. Once you create a user you may select its Role: Admin, Teacher or Parent.

**Comment by francoisjacquet** [comment]
Thank you @danfelbm
