### ISSUE TITLE
About RosarioSIS

### ISSUE THREAD

**Issue by cursogalileu** [francoisjacquet/rosariosis#135]
After 38 years in IT consulting I want to present you my CONGRATULATIONS! Rosario SIS is really a great software for Schools and it is completely free to be modified. I worked for SIS on Universities in Brazil. I worked with SOCRATES (from IBM) and with SOLSTAR (from MJData). Also Financial systems. Thank you to give me a tool like Rosario SIS.

**Comment by francoisjacquet** [comment]
Thank you for your kind words @cursogalileu
