### ISSUE TITLE
Create subjects for students? Need help

### ISSUE THREAD

**Issue by tuyendvhpu** [francoisjacquet/rosariosis#137]
After installation, I can't create news subjects.

**Comment by danfelbm** [comment]
Hello,

Can you please let us know how to reproduce the problem?, are you trying to create them in Scheduling > Setup > Courses > Subjects? Are you receiving a Database-related error?, or maybe this option does not appear in the Menu?

Regards

**Comment by tuyendvhpu** [comment]
ok, I find to create a subject. Tks!

**Comment by danfelbm** [comment]
Great. Anything you need!

Regards.

**Comment by danfelbm** [comment]
Great. Anything you need!

Please don't forget to review the Wiki https://github.com/francoisjacquet/rosariosis/wiki
Is full of useful tips to get started.

Regards.

**Comment by tuyendvhpu** [comment]
Continue to install Moodle plugin, when I click to configure plugin on school setup > Configuration > Modules plugin:
Ajax get error
Status: error
HTTP status: Internal Server Error
URL: http://localhost:8080/rosariosis/Modules.php?modname=School_Setup/Configuration.php&tab=plugins&modfunc=config&plugin=Moodle 
I stuck here, can anyone help?

**Comment by danfelbm** [comment]
Hello,

Internal Server Error could be several things. Do you meet the minimum requirements to use RosarioSIS? https://www.rosariosis.org/download/

Did you perform a local test installation?, if so, what software did you use? (mappstack?); because it would be useful to see the logs and find out what the actual error might be. With Mappstack / Bitnami please refer to the following link: https://wiki.bitnami.com/Components/Apache#Check_the_apache_error_file and paste here the last lines of your log file.

Also, does the URL http://localohst:8080/rosariosis/diagnostic.php throws any error message?

Thanks.

**Comment by tuyendvhpu** [comment]
Hi
Thanks for support. Here's wapstack log file:

[Mon Apr 18 20:37:45.684236 2016] [:error] [pid 36184:tid 1260] [client 185.25.151.159:35653] script 'C:/wappstack/apache2/htdocs/testproxy.php' not found or unable to stat
[Mon Apr 18 21:28:08.028236 2016] [:error] [pid 36184:tid 1260] [client 116.101.144.114:48966] PHP Parse error:  syntax error, unexpected ')', expecting :: (T_PAAMAYIM_NEKUDOTAYIM) in C:\\wappstack\\apache2\\htdocs\\rosariosis\\plugins\\Moodle\\config.inc.php on line 132, referer: http://203.162.241.106:8080/rosariosis/Modules.php?modname=School_Setup/Configuration.php&tab=plugins&modfunc=activate&plugin=Moodle

I can't find testproxy.php in wappstack directory.

**Comment by francoisjacquet** [comment]
Hi @tuyendvhpu 

Thank you for posting the relevant `error.log` line.

The `plugins/Moodle/config.inc.php` file as of [version 2.8.](https://github.com/francoisjacquet/rosariosis/blob/mobile/plugins/Moodle/config.inc.php#L81), does not contain any line number 132.

The [2.9-beta1 version](https://github.com/francoisjacquet/rosariosis/blob/2.9-dev/plugins/Moodle/config.inc.php#L132) of the same file, on line number 132, does not contain any error.

You must have downloaded the _alpha_ version. Please rebase the beta or switch to the lastest stable 2.8 release instead: https://github.com/francoisjacquet/rosariosis/releases

**Comment by tuyendvhpu** [comment]
Thank you very much!
