### ISSUE TITLE
 It does not work in Ubuntu 16.04

### ISSUE THREAD

**Issue by domingo0007** [francoisjacquet/rosariosis#138]
I tried the stable version and the beta version of RosarioSis and I could not make it work in Ubuntu 16.04.
It is just out, but one that will install new server version and would like to be able to run RosarioSis.
Has anyone been able to operate in 16.04?

**Comment by danfelbm** [comment]
Hello,

While I have not tried it in Ubuntu 16.04, I encourage you to stick to the requirements mentioned in https://github.com/francoisjacquet/rosariosis/blob/mobile/INSTALL

What is your version of Apache, PHP and PostgreSQL?, what error did you receive? (remember to check the logs to perform a better diagnosis of what can be causing the error)

Regards

**Comment by domingo0007** [comment]
Ubuntu 16.04 comes with PHP 7 and Postgres 9.5
When I set up the database and RosarioSis cargo loads a blank page.

**Comment by danfelbm** [comment]
Hi there,

What does /var/log/apache2/error.log say?

Thank you,
Regards

**Comment by domingo0007** [comment]
Good Morning. Thanks for your help.
I continued trying and I managed to make it work.
I have enabled several extensions of PHP and can not remember what exactly. Today during the day'll do the installation in a new virtual machine and write here so that others have the solution too.

**Comment by francoisjacquet** [comment]
@danfelbm thank you for your help.

@domingo0007 the [_diagnostic.php_](https://github.com/francoisjacquet/rosariosis/blob/mobile/INSTALL#L98) page is here to help you spot the missing PHP extensions & other configuration errors.

Please let us know here which PHP extensions are not installed by default on Ubuntu 16.04.

Thank you.

**Comment by domingo0007** [comment]
mbstring missing
It works out like this:

sudo apt-get install php-mbstring php7.0-mbstring php-gettext
sudo service apache2 restart

**Comment by domingo0007** [comment]
when diagnostic.php ran out a blank page.

**Comment by danfelbm** [comment]
Hello,

Is RosarioSIS currently working? nevertheless, what does the file /var/log/apache2/error.log say?

Thank you,
Regards

**Comment by domingo0007** [comment]
error.log
My document root is: /etc/escuela/html
My domain is: www.escuela.loc


[Sun Apr 24 00:14:12.719200 2016] [mpm_prefork:notice] [pid 1046] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Sun Apr 24 00:14:12.719325 2016] [core:notice] [pid 1046] AH00094: Command line: '/usr/sbin/apache2'
[Sun Apr 24 00:35:14.418358 2016] [mpm_prefork:notice] [pid 1046] AH00169: caught SIGTERM, shutting down
[Mon Apr 25 11:00:21.326008 2016] [mpm_prefork:notice] [pid 1142] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Mon Apr 25 11:00:21.364216 2016] [core:notice] [pid 1142] AH00094: Command line: '/usr/sbin/apache2'
[Mon Apr 25 13:02:08.912609 2016] [mpm_prefork:notice] [pid 1142] AH00169: caught SIGTERM, shutting down
[Mon Apr 25 13:02:09.847046 2016] [mpm_prefork:notice] [pid 3877] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Mon Apr 25 13:02:09.847151 2016] [core:notice] [pid 3877] AH00094: Command line: '/usr/sbin/apache2'
[Mon Apr 25 13:05:18.056951 2016] [mpm_prefork:notice] [pid 3877] AH00169: caught SIGTERM, shutting down
[Mon Apr 25 13:05:19.230762 2016] [mpm_prefork:notice] [pid 4043] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Mon Apr 25 13:05:19.230871 2016] [core:notice] [pid 4043] AH00094: Command line: '/usr/sbin/apache2'
[Mon Apr 25 13:07:25.846757 2016] [mpm_prefork:notice] [pid 4043] AH00169: caught SIGTERM, shutting down
[Mon Apr 25 13:07:26.938881 2016] [mpm_prefork:notice] [pid 4731] AH00163: Apache/2.4.18 (Ubuntu) mod_auth_pgsql/2.0.3 configured -- resuming normal operations
[Mon Apr 25 13:07:26.939030 2016] [core:notice] [pid 4731] AH00094: Command line: '/usr/sbin/apache2'
[Mon Apr 25 13:07:44.350645 2016] [mpm_prefork:notice] [pid 4731] AH00169: caught SIGTERM, shutting down
[Mon Apr 25 13:09:52.124498 2016] [mpm_prefork:notice] [pid 1120] AH00163: Apache/2.4.18 (Ubuntu) mod_auth_pgsql/2.0.3 configured -- resuming normal operations
[Mon Apr 25 13:09:52.140308 2016] [core:notice] [pid 1120] AH00094: Command line: '/usr/sbin/apache2'
[Mon Apr 25 13:14:23.578385 2016] [mpm_prefork:notice] [pid 1120] AH00171: Graceful restart requested, doing restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Mon Apr 25 13:14:23.788625 2016] [mpm_prefork:notice] [pid 1120] AH00163: Apache/2.4.18 (Ubuntu) mod_auth_pgsql/2.0.3 configured -- resuming normal operations
[Mon Apr 25 13:14:23.788656 2016] [core:notice] [pid 1120] AH00094: Command line: '/usr/sbin/apache2'
[Mon Apr 25 13:14:24.421117 2016] [mpm_prefork:notice] [pid 1120] AH00171: Graceful restart requested, doing restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Mon Apr 25 13:14:24.550940 2016] [mpm_prefork:notice] [pid 1120] AH00163: Apache/2.4.18 (Ubuntu) mod_auth_pgsql/2.0.3 configured -- resuming normal operations
[Mon Apr 25 13:14:24.550970 2016] [core:notice] [pid 1120] AH00094: Command line: '/usr/sbin/apache2'
[Mon Apr 25 13:18:30.764585 2016] [mpm_prefork:notice] [pid 1120] AH00169: caught SIGTERM, shutting down
[Mon Apr 25 13:19:20.688952 2016] [mpm_prefork:notice] [pid 1114] AH00163: Apache/2.4.18 (Ubuntu) mod_auth_pgsql/2.0.3 configured -- resuming normal operations
[Mon Apr 25 13:19:20.963198 2016] [core:notice] [pid 1114] AH00094: Command line: '/usr/sbin/apache2'
[Mon Apr 25 13:39:41.454148 2016] [mpm_prefork:notice] [pid 1114] AH00169: caught SIGTERM, shutting down
[Mon Apr 25 13:39:42.633634 2016] [mpm_prefork:notice] [pid 1796] AH00163: Apache/2.4.18 (Ubuntu) mod_auth_pgsql/2.0.3 configured -- resuming normal operations
[Mon Apr 25 13:39:42.633739 2016] [core:notice] [pid 1796] AH00094: Command line: '/usr/sbin/apache2'
[Mon Apr 25 13:40:40.099606 2016] [:error] [pid 1802] [client 192.168.0.100:44928] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Misc has a deprecated constructor in /usr/share/phppgadmin/classes/Misc.php on line 8
[Mon Apr 25 13:40:42.224730 2016] [:error] [pid 1800] [client 192.168.0.100:44978] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; ArrayRecordSet has a deprecated constructor in /usr/share/phppgadmin/classes/ArrayRecordSet.php on line 8, referer: http://www.escuela.loc/phppgadmin/browser.php
[Mon Apr 25 13:40:52.069924 2016] [:error] [pid 1806] [client 192.168.0.100:45218] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Connection has a deprecated constructor in /usr/share/phppgadmin/classes/database/Connection.php on line 11, referer: http://www.escuela.loc/phppgadmin/redirect.php?subject=server&server=localhost%3A5432%3Aallow
[Mon Apr 25 13:40:52.113808 2016] [:error] [pid 1806] [client 192.168.0.100:45218] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; ADODB_base has a deprecated constructor in /usr/share/phppgadmin/classes/database/ADODB_base.php on line 12, referer: http://www.escuela.loc/phppgadmin/redirect.php?subject=server&server=localhost%3A5432%3Aallow
[Mon Apr 25 13:40:52.898907 2016] [:error] [pid 1806] [client 192.168.0.100:45218] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Postgres has a deprecated constructor in /usr/share/phppgadmin/classes/database/Postgres.php on line 12, referer: http://www.escuela.loc/phppgadmin/redirect.php?subject=server&server=localhost%3A5432%3Aallow
[Mon Apr 25 13:44:41.972327 2016] [:error] [pid 1871] [client 192.168.0.100:49786] PHP Fatal error:  Uncaught Error: Call to undefined function mb_internal_encoding() in /var/www/escuela/html/Warehouse.php:85\nStack trace:\n#0 /var/www/escuela/html/diagnostic.php(21): include()\n#1 {main}\n  thrown in /var/www/escuela/html/Warehouse.php on line 85
[Mon Apr 25 13:44:50.823157 2016] [:error] [pid 1803] [client 192.168.0.100:50054] PHP Fatal error:  Uncaught Error: Call to undefined function mb_internal_encoding() in /var/www/escuela/html/Warehouse.php:85\nStack trace:\n#0 /var/www/escuela/html/index.php(6): include()\n#1 {main}\n  thrown in /var/www/escuela/html/Warehouse.php on line 85
[Mon Apr 25 13:45:35.450712 2016] [mpm_prefork:notice] [pid 1796] AH00171: Graceful restart requested, doing restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Mon Apr 25 13:45:36.163406 2016] [mpm_prefork:notice] [pid 1796] AH00163: Apache/2.4.18 (Ubuntu) mod_auth_pgsql/2.0.3 configured -- resuming normal operations
[Mon Apr 25 13:45:36.163459 2016] [core:notice] [pid 1796] AH00094: Command line: '/usr/sbin/apache2'
[Mon Apr 25 13:45:36.267261 2016] [mpm_prefork:notice] [pid 1796] AH00171: Graceful restart requested, doing restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Mon Apr 25 13:45:36.500375 2016] [mpm_prefork:notice] [pid 1796] AH00163: Apache/2.4.18 (Ubuntu) mod_auth_pgsql/2.0.3 configured -- resuming normal operations
[Mon Apr 25 13:45:36.500407 2016] [core:notice] [pid 1796] AH00094: Command line: '/usr/sbin/apache2'
[Mon Apr 25 13:47:24.944965 2016] [mpm_prefork:notice] [pid 1796] AH00169: caught SIGTERM, shutting down
[Mon Apr 25 13:47:26.336089 2016] [mpm_prefork:notice] [pid 6331] AH00163: Apache/2.4.18 (Ubuntu) mod_auth_pgsql/2.0.3 configured -- resuming normal operations
[Mon Apr 25 13:47:26.336201 2016] [core:notice] [pid 6331] AH00094: Command line: '/usr/sbin/apache2'
[Mon Apr 25 15:47:22.730202 2016] [mpm_prefork:notice] [pid 1116] AH00163: Apache/2.4.18 (Ubuntu) mod_auth_pgsql/2.0.3 configured -- resuming normal operations
[Mon Apr 25 15:47:22.762984 2016] [core:notice] [pid 1116] AH00094: Command line: '/usr/sbin/apache2'
[Mon Apr 25 16:09:30.621743 2016] [:error] [pid 1194] [client 10.0.0.19:48926] PHP Warning:  mkdir(): Permiso denegado in /var/www/escuela/html/ProgramFunctions/FileUpload.fnc.php on line 33, referer: http://www.escuela.loc/Modules.php?modname=Students/Student.php&category_id=1&modfunc=update

**Comment by francoisjacquet** [comment]
@domingo0007 you will probably need to install the _mbstring_ PHP extension.

Please also check [this wiki page](https://github.com/francoisjacquet/rosariosis/wiki/Photo-upload-issue) for help with file upload errors.
