### ISSUE TITLE
Instalation Problem windows

### ISSUE THREAD

**Issue by thf81** [francoisjacquet/rosariosis#140]
Hello, 

I have followed the tutorial for windows but in the end I have this message

config.inc.php file not found. Please read the installation directions.

Help please...

cordially

**Comment by danfelbm** [comment]
Hello,

Have you renamed config.inc.sample.php to config.inc.php?, can you please run the diagnostic.php and let us know its output?

Also, what does \apache2\logs\error.log say?

Regards

**Comment by francoisjacquet** [comment]
Thank you @danfelbm 

@thf81 please do not hesitate to tell us if this solution worked for you.
