### ISSUE TITLE
Cannot access handbook

### ISSUE THREAD

**Issue by manzzaid** [francoisjacquet/rosariosis#141]
trying to access administrator hankbook, after clicking the link on the resources page, the page (help.php) just keeps loading and timeout.

**Comment by francoisjacquet** [comment]
Hello @manzzaid 

Please first try to generate an HTML Handbook:
empty the wkhtmltopdf path variable in the `config.inc.php` file:
`$wkhtmltopdfPath = '';`

Also please check your Apache error log and post any relevant error here.

**Comment by manzzaid** [comment]
Removing the path solved the issue.
thanks
