### ISSUE TITLE
I can not create classes

### ISSUE THREAD

**Issue by ramblas98** [francoisjacquet/rosariosis#144]
Please could you help me with the following error?
I try to add the first class
![captura01](https://cloud.githubusercontent.com/assets/911171/15838325/d65b7b3a-2c13-11e6-8757-d92beafc163d.PNG)

I add and select all data
![captura02](https://cloud.githubusercontent.com/assets/911171/15838335/e9d12ee4-2c13-11e6-84e6-4e703890c70c.PNG)

when I save , the following error occurs as a result
![captura03](https://cloud.githubusercontent.com/assets/911171/15838342/f1ef2a5e-2c13-11e6-9de2-e089101cec0b.PNG)

The SQL statement that causes the error is:

SELECT PERIOD_ID,DAYS FROM COURSE_PERIOD_SCHOOL_PERIODS WHERE COURSE_PERIOD_ID='new'

The server has the following software installed:

Debian 8.3 686
RosarioSIS 2.8 updated to 2.9.2
Apache 2.4
Postgresql 9.4.5
Php 5.6.17

Thank you

**Comment by francoisjacquet** [comment]
Hello @ramblas98 
Thank you for reporting the error and attaching screenshots.
The error will be fixed in the next release.
In the meantime, please enter _valid numeric data_ for the **Credits** field (no commas "," allowed) to avoid the error.
