### ISSUE TITLE
I can not find classes

### ISSUE THREAD

**Issue by ramblas98** [francoisjacquet/rosariosis#145]
Hi Fracrois, thank you very much for the previous answer. Now I 'm loading the classes and I do not know if it's a programming error or data entry .

Why i can not fin some classes? For example:

For this subject effectively day of class it is shown
![captura-clases-01](https://cloud.githubusercontent.com/assets/911171/15895143/18a2d798-2d60-11e6-9639-5592571136dd.PNG)

But not for this other subject
![captura-clases-02](https://cloud.githubusercontent.com/assets/911171/15895172/48724e36-2d60-11e6-8698-5032f5bc0f3b.PNG)

If I find the subject then appears
![captura-clases-03](https://cloud.githubusercontent.com/assets/911171/15895178/5196c08c-2d60-11e6-84b8-6364308724af.PNG)

Please, could you tell me what is wrong?

**Comment by ramblas98** [comment]
I solve the above problem by deleting all subjects and courses. I can already load the classes but when given at the same time but different day not accept it.

![Uploading Captura-clases-04.PNG…]()

**Comment by ramblas98** [comment]
![captura-clases-04](https://cloud.githubusercontent.com/assets/911171/15932655/ea13a924-2e32-11e6-8ecf-e6e65f70600d.PNG)

**Comment by francoisjacquet** [comment]
Hello @ramblas98 

For all your questions about RosarioSIS use and configuration, please head to http://rosariosis.org/es/services for email support (in Spanish).
