### ISSUE TITLE
Question: How do I perform updates?

### ISSUE THREAD

**Issue by desajoao** [francoisjacquet/rosariosis#146]
Hi there,

I was wondering if anyone has instructions on how to perform system updates. I am currently running version 2.9.1.

Thanks,
Joao

**Comment by francoisjacquet** [comment]
Hi @desajoao 

RosarioSIS upgrades are performed overwriting the new files over the old ones, as mentioned in each [release notes](https://github.com/francoisjacquet/rosariosis/releases/).
