### ISSUE TITLE
Rollover problem - cannot roll over students

### ISSUE THREAD

**Issue by desajoao** [francoisjacquet/rosariosis#147]
Hi all,

I am having trouble rolling over students. Is anyone else experiencing this? The system returns the following message:
<img width="829" alt="screen shot 2016-06-10 at 8 09 34 pm" src="https://cloud.githubusercontent.com/assets/19788179/15981840/52844aec-2f49-11e6-80e6-60773d551152.png">

**Comment by desajoao** [comment]
Solved-- I had rolled over enrollment codes before students, as instructed, and when I later tried to roll students I got the message above. I then tried to roll students and enrollment codes at the same time, which worked.

**Comment by francoisjacquet** [comment]
Hi @desajoao 

Thank you for reporting the SQL error.
We could not reproduce it rolling the data except the enrollment codes.

Perhaps you received an automatic **email** related to this DB error?
In which case it contains useful debug information you could post here.

**Comment by desajoao** [comment]
Hi @francoisjacquet,

I received the message when I tried to roll students _after_ rolling the codes, but when I rolled them both at the same time, I was successful. No email received...
