### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by abcsis** [francoisjacquet/rosariosis#149]
I have activated Email module, but does not appear in menu. Refer screenshot.
<img width="842" alt="capture" src="https://cloud.githubusercontent.com/assets/20058368/16219433/e0be5876-37b8-11e6-8b92-b323d08cf59c.PNG">

**Comment by francoisjacquet** [comment]
Hello @abcsis 

The Email module does not have a top level entry in the menu.
Please refer to the description (you can click on the _Email_ link as seen on your screenshot) for where you will find the added programs: https://github.com/francoisjacquet/Email#description
