### ISSUE TITLE
Unknown ajax error

### ISSUE THREAD

**Issue by abcsis** [francoisjacquet/rosariosis#150]
Sometimes browse through any menu items, will pop up the attached error, after that page loaded. What is this error related? How to resolve it?
<img width="352" alt="capture" src="https://cloud.githubusercontent.com/assets/20058368/16219519/88a12c8a-37b9-11e6-85f0-620904682a62.PNG">

**Comment by francoisjacquet** [comment]
Hello @abcsis 

You may find more info in your Apache's `error.log` file **if** the error is related to your server / PHP.
**If** it is related to a network failure (_timeout, abort, general network error_), you should simply reintent or get a better internet connection or get a better server (ie. this does not happen on [rosariosis.org](http://rosariosis.org/services)).

We will try to enhance the AJAX error messages so they are more user friendly in a future version.

**Comment by francoisjacquet** [comment]
See https://github.com/francoisjacquet/rosariosis/commit/850f379f9e755b555d8a6d466118aa7f8358ac5c
