### ISSUE TITLE
You must accept cookies to use RosarioSIS

### ISSUE THREAD

**Issue by abcsis** [francoisjacquet/rosariosis#151]
Unable to login using IE or safari, keep show "You must accept cookies to use RosarioSIS"

But the cookies setting is enabled!!! No such issue with Firefox or Chrome. Please help.

**Comment by francoisjacquet** [comment]
Hello @abcsis 

Please refer to https://github.com/francoisjacquet/rosariosis/issues/109 , https://github.com/francoisjacquet/rosariosis/issues/101

Please reopen the issue providing [more details](https://github.com/francoisjacquet/rosariosis/blob/mobile/CONTRIBUTING.md#new-issue) to help us reproduce the problem **if** the above mentioned fixes did not help.
