### ISSUE TITLE
Blank grades logic

### ISSUE THREAD

**Issue by danfelbm** [francoisjacquet/rosariosis#153]
Hello there,

I've been using the platform for a few months now and we've found it very very useful. However, there is a strange behaviour with the way Final averages are generated.

When there are blank fields (unfilled), they are counted as 0s. That affects the final and partial grades. I think the totals algorithm should ignore blank fields when generating the final grade. If a student gets a bad grade, then teachers should put 0 and that's it, the grade will be counted.

This would also give a more accurate partial report, since many assignments can be generated starting the marking period, but are not graded until the end of it; and by averaging blank fields as 0, then calculating the actual partial percentage becomes difficult for the average user.

Any thoughts?

**Comment by danfelbm** [comment]
I was thinking in [/modules/Grades/Grades.php](https://github.com/francoisjacquet/rosariosis/blob/mobile/modules/Grades/Grades.php#L344) the following could be added `AND gg.POINTS IS NOT NULL` as a quick fix. (the same for InputFinalGrades.php and wherever it happens)

This would ensure that partial/total points and final average only count filled fields...

**Comment by francoisjacquet** [comment]
Hello @danfelbm 

Concerning the **partial** Gradebook Grades total, blank / empty grades will be taken in account **only if**:
- The assigned date and the due date are not set.
- The assigned date and the due date are past the current date.
- The marking period's end date is past the current date.

So, one solution would be to set the assigned date and/or the due date.

Line [344](https://github.com/francoisjacquet/rosariosis/blob/mobile/modules/Grades/Grades.php#L344) may look really long to read, yet it already contains the `gg.POINTS IS NOT NULL` along with the above mentioned conditions.

Now, the **final** Gradebook Grades total will consider `NULL` grade points as 0 indeed. If you want to _Excuse_ a Student, simply enter an asterisk `*` in the points field. The Assignment will be consequently  skipped from the Total.

We remind you that for all your questions related to RosarioSIS use, we can offer you email support, please contact us at http://rosariosis.org/services

**Comment by francoisjacquet** [comment]
Closed for inactivity.
