### ISSUE TITLE
The requested URL /rosariosis/ was not found on this server.

### ISSUE THREAD

**Issue by siteBoy** [francoisjacquet/rosariosis#155]
Hello great people great company 
Hi francoisjacquet , I follow your instruction step by step about the  installation,after finished the installation i can access the application, it was giving the following error.The requested URL /rosariosis/ was not found on this server. please am look forward to here from you.
Thanks.

**Comment by francoisjacquet** [comment]
Hello @siteBoy 

We will need some more information about your server, browser, RosarioSIS, URL configuration.
Please head to [CONTRIBUTING.md](https://github.com/francoisjacquet/rosariosis/blob/mobile/CONTRIBUTING.md) for recommendations on how to post an issue.

Please note that installation problems may not be solved here. Prefer our [email support service](https://www.rosariosis.org/services/).

**Comment by siteBoy** [comment]
Thanks francoisjacquet i corrected my mistake,instead of rosariosis-2.9.5 i rote rosariosis.
