### ISSUE TITLE
config.inc.php file not found. Please read the installation directions.

### ISSUE THREAD

**Issue by siteBoy** [francoisjacquet/rosariosis#156]
I follow the step by step installation documentation,i don't know what is going rung please help me out.
config.inc.php file not found. Please read the installation directions.

**Comment by siteBoy** [comment]
This is what i found in open error log.

[Sat Jul 23 02:01:07.242253 2016] [:error] [pid 2916:tid 1096] [client 127.0.0.1:50806] PHP Warning:  include_once(): Failed opening 'config.inc.php' for inclusion (include_path='.;C:/Bitnami/wappstack-5.4.45-0/php/PEAR') in C:\Bitnami\wappstack-5.4.45-0\apache2\htdocs\rosariosis-2.9.5\Warehouse.php on line 25.

i did not know what to do about this

**Comment by francoisjacquet** [comment]
The error states the `config.inc.php` file was not found. You need to create it copying the example `config.inc.sample.php` file you will find at the root of the project. Then you also need to edit it just as told in the installation directions.
