### ISSUE TITLE
Unable to delete Period

### ISSUE THREAD

**Issue by dabest1** [francoisjacquet/rosariosis#157]
Unable to delete a Period from Course Period. There needs to be a delete option added or a Period needs to be removed once all Days are unselected.

How to reproduce:
Go to Scheduling -> Courses.
Select a Subject.
Select a Cource.
Select a Course Period.
Click on New Period.
Populate some of the fields.
Save.
Then try to remove one of the periods. There is no option for that. Unselecting all Days does not work.

RosarioSIS version 2.9.5

**Comment by francoisjacquet** [comment]
Hello @dabest1 

Thank you for reporting the issue. This is a regression since version 2.9.

The fix will be available in the next release. You can grab it immediately here: https://github.com/francoisjacquet/rosariosis/archive/mobile.zip
