### ISSUE TITLE
Added students are inactive

### ISSUE THREAD

**Issue by dabest1** [francoisjacquet/rosariosis#158]
After adding students and enrolling them and assigning a Course Period, they are still showing up as Inactive. The only Active student is the one that was builtin. Looking through the Wiki and the Handbook, I cannot find any information on how to mark a student as Active. I tried to go through all the functions in the SIS and can't find there either. Why are students Inactive and how to make them Active?

**Comment by francoisjacquet** [comment]
Hello @dabest1 

Students are **inactive** if:
- the _Attendance Start date_ is after today
- or the _Drop date_ if before today
  (see _Students > Student Info > Enrollment Record_).

If you need support for RosarioSIS use, please contact us at https://www.rosariosis.org/services/

**Comment by dabest1** [comment]
Thank you for clarifying the meaning of Inactive.
