### ISSUE TITLE
Unable to delete Course

### ISSUE THREAD

**Issue by dabest1** [francoisjacquet/rosariosis#159]
Unable to delete a Period from Student Schedule. It seems like there needs to be a delete option for a Period added to a Student Schedule, so that mistakes can be corrected.

How to reproduce:
Go to Scheduling -> Student Schedule.
Search for some student.
Add Course.
Try to delete Course. There is no option for deleting Course.

RosarioSIS version 2.9.5

**Comment by francoisjacquet** [comment]
Hello @dabest1 

Thank you for reporting the problem.
The Help texts have been updated:

> To drop an existing course, select the "Dropped" date next to the course you want to drop from the student's schedule.
>   If you select a "Dropped" date prior to the "Enrolled" date, the course will be removed and you will be asked to confirm the removal of the associated absences and grades records.

**Comment by dabest1** [comment]
Thanks.
