### ISSUE TITLE
Activity Log for Users and Students

### ISSUE THREAD

**Issue by desajoao** [francoisjacquet/rosariosis#160]
Hi @francoisjacquet:

I just wanted to suggest that there be an activity log report for users and students. That way, we could tighten security by being able to spot unusual activity on a certain account. For example, a student with an administrative password would be able to login with no problems, and this could go on forever so long as there is no way to check user activity on a user-by-user level, as opposed to the server level.

Hope you find this a good suggestion.

**Comment by francoisjacquet** [comment]
Hello @desajoao 

Logging users and students activity is a good suggestion, thank you.
You can already check the last time a user or a student logged in (and failed logins) within RosarioSIS, which can help confirm suspicions:
(Users list expanded view)
![screenshot from 2016-07-27 11 07 41](https://cloud.githubusercontent.com/assets/4723501/17182798/6fac5c52-53ea-11e6-9dc3-8efcdc3805a2.png)

The downside of a logging system is that it usually slows down the system.

You or anybody interested in sponsoring the development of this feature can contact us at https://www.rosariosis.org/services/

**Comment by dpredster** [comment]
Hi @desajoao &  @francoisjacquet 

Maybe I can be of some help. I am currently working on an addon to the software that allows you to do that. It's a modification to another open source sis. So far I have gotten it to log both successful as well as failed logins. Just have to add a function to delete the log. I'm willing to share my work if you are interested.

![access_log](https://cloud.githubusercontent.com/assets/3442375/17232561/021897d8-54f7-11e6-9287-f46fe277eb0b.png)

**Comment by danfelbm** [comment]
That theme looks beautiful :) is that your work?

**Comment by dpredster** [comment]
@danfelbm 

Thanks. It is my work. It's more like an enhancement than a theme.

**Comment by danfelbm** [comment]
It looks great! 👍  good work

**Comment by desajoao** [comment]
Hi @dpredster:

I am very much interested in your work. My e-mail is [desajoao@jtcenter.us](mailto:desajoao@jtcenter.us). Can you contact me so we can discuss this further?

Regards,
Joao

**Comment by francoisjacquet** [comment]
Hello @dpredster 

Please let us know when you have published your work (on Github or anywhere else), I will surely have a look at it.

Thank you.

**Comment by dpredster** [comment]
@francoisjacquet 

No problem. I will.

Thank you for all your hard work.

**Comment by dpredster** [comment]
Hi @francoisjacquet 

I have attached the files with the changes I have made for you to review it and let me know what you think.

**Comment by francoisjacquet** [comment]
Hello @dpredster 

Thank you for sharing your code.
I have reviewed your code inspired by OpenSIS.
For others to know, it _only records successful logins_, which in my opinion is more than enough.

I can add some actions hooks on the `index.php` page so you can publish your work as an extra module  that can be installed from _School Configuration > Modules_.

You can start looking at the [Example module](https://github.com/francoisjacquet/Example)

Please let me know if you are interested, I will guide you more.

**Comment by dpredster** [comment]
Hi @francoisjacquet 

It would be an honor to contribute this code as a module for RosarioSIS.  I have benefited immensely from your work and I am happy to give back to the project.

I have followed your Example module and came up with the attached module. I have also modified the changes required in index.php which are documented in the readme.txt file.

The new module now records both successful as well as unsuccessful login attempts however it only shows User Profiles for successful logins. 

I look forward to you reviewing the module and letting me know what you think

Regards,
Dave

The module can now be found at http://github.com/dpredster/Access_Log

**Comment by francoisjacquet** [comment]
Hello @dpredster, @desajoao,

The Access Log module has been included in [RosarioSIS 3.0](https://github.com/francoisjacquet/rosariosis/blob/mobile/CHANGES.md#changes-in-30).
You can safely delete the extra module after upgrading.

It has been enhanced too: **User Agent** info is now saved and displayed, plus a link to the User / Student page has been implemented.

For those who had not installed it, **after upgrading** you can activate it in the _Users > Profiles_ program.

Thank you.
