### ISSUE TITLE
Combining Widget parameters

### ISSUE THREAD

**Issue by danfelbm** [francoisjacquet/rosariosis#161]
Hello there,

I'm trying to generate datasets by mixing the Widget options. However it seems that "Course" and "Grade" can't be mixed.

When generating a transcript, for example (because it already allows you to select both a Course and Grades by default), it won't use both to render the information... If I select a course only, it works; if I select Grades only, it works. But not if I select both. It simply ignores the course and only shows the Grades info.

http://i.imgur.com/V6BXfo3.png
http://i.imgur.com/mXF39Qt.png

Any suggestion?

**Comment by francoisjacquet** [comment]
Thank you @danfelbm for reporting the issue.

The search terms for the Letter Grade widget have been fixed:
![screenshot from 2016-07-29 14 26 15](https://cloud.githubusercontent.com/assets/4723501/17260898/9ac5fd26-5598-11e6-9bf1-67c0293f81d8.png)
