### ISSUE TITLE
Passing Grade is NOT Awarding Credit

### ISSUE THREAD

**Issue by desajoao** [francoisjacquet/rosariosis#162]
Hi @francoisjacquet:

I am currently experiencing an issue-- students are not receiving credit after earning a passing grade. I have attached the screenshots of my grade setup:

<img width="961" alt="screen shot 2016-07-29 at 2 39 53 pm" src="https://cloud.githubusercontent.com/assets/19788179/17259738/ef53cdee-559a-11e6-877c-3c5f2a4f454e.png">

<img width="958" alt="screen shot 2016-07-29 at 2 40 06 pm" src="https://cloud.githubusercontent.com/assets/19788179/17259742/f4022d22-559a-11e6-977c-a92f1e0838c1.png">

<img width="939" alt="screen shot 2016-07-29 at 2 41 12 pm" src="https://cloud.githubusercontent.com/assets/19788179/17259750/faa9421e-559a-11e6-941e-2c3d973a7f37.png">

<img width="954" alt="screen shot 2016-07-29 at 2 41 20 pm" src="https://cloud.githubusercontent.com/assets/19788179/17259758/fe93e5fa-559a-11e6-8f5c-cbe44346e67f.png">

Where A-F (A+) is the main grading scale.

**Comment by francoisjacquet** [comment]
Hello @desajoao 

The minimum passing grade is not a _percentage_, but a grade.
If your base grade scale is set to 4 points, the _Minimum Passing Grade_ should logically be **inferior to 4**.

Now, as for the History Grades, you should manually set the _Credits earned_ as they are not related to the Grade scales. History grades are usually used to import student grades from another school, where the grade scale can be different from the one in your school.

For any question you may have regarding RosarioSIS use or configuration, we can provide you with personalized support at https://www.rosariosis.org/services/
