### ISSUE TITLE
Locking past marking periods

### ISSUE THREAD

**Issue by danfelbm** [francoisjacquet/rosariosis#164]
Hello,

There could be circumstances in which a Teacher access the platform but isn't in the current marking period, and without noticing it create an Assignment and even grade it. Unfortunately this happened to us with some inexperienced users.

There isn't a tool to transfer the assignments or Grades, so this had to be done manually. It would be great if RosarioSIS had a setting that allows administrators to enable or disable new Assignment and Grades on past marking periods (including a warning message saying that that period is closed), and therefore preventing users from messing with the information. This could also prevent unwanted modifications of previous grades...

What do you guys think?

Overall, great platform, thanks for your hard work...

Regards

**Comment by francoisjacquet** [comment]
Hello @danfelbm 

I understand the problem teachers face. Maybe we could both:
- Add the Marking Period name to the Assignments program title, for example : "**Quarter 1** Assignments"
- Display a Warning when teachers are not in the current quarter, when creating a new Assignment.

What would you think of this solution?

**Comment by danfelbm** [comment]
Hello François,

That actually sounds great! Is simple and it would be very useful for teachers or any user that is browsing old marking periods.

Regards
