### ISSUE TITLE
School Setup Module Mission on Administrator 

### ISSUE THREAD

**Issue by dmongking** [francoisjacquet/rosariosis#166]
Hi,

I found that the School Setup Module is missing. I was told to check the 'can use' and 'can edit' on permissions of the user profile (administrator), but there is no School Setup even on the user profiles so there is really no way for me to check the boxes that I am supposed to check. Last week, we were still using the School Setup every day as the Calendar is there, but by the end of last week, we could not access it anymore. 

Please check.

Thanks!
![2lis](https://cloud.githubusercontent.com/assets/22438124/18821495/ec9181e6-83d0-11e6-8244-1f1df8b51cfd.JPG)

**Comment by francoisjacquet** [comment]
For reference:
As what was concluded by email support, @dmongking had its `modules/School_Setup/` files missing.
