### ISSUE TITLE
Class ranking (question)

### ISSUE THREAD

**Issue by danfelbm** [francoisjacquet/rosariosis#167]
Hello there,

I was wondering if RosarioSIS can generate a list of students based on the ranking (averaging the total final grades and therefore a ranked list), per grade.

Is this possible?

Regards

**Comment by francoisjacquet** [comment]
Hello @danfelbm 

The "GPA / Class Rank List" program in the Grades module does that:
![screenshot from 2016-10-28 15 15 33](https://cloud.githubusercontent.com/assets/4723501/19807673/8441ceba-9d21-11e6-9bd1-2c2342b64ee9.png)

If you need help to generate class ranks, please contact us at https://www.rosariosis.org/services/

**Comment by francoisjacquet** [comment]
Closed for inactivity.
