### ISSUE TITLE
integrar un modulo para biblioteca seria bueno

### ISSUE THREAD

**Issue by avancelcom** [francoisjacquet/rosariosis#168]
me parece bueno integrar un modulo biblioteca que mencione los prestamos de libros, fechas

De antemano felicidades por este gran software 

desde Colombia Yonathan

**Comment by francoisjacquet** [comment]
Hello @avancelcom 

Thank you for your kind words.
Have you tried [PMB](http://www.pmbservices.fr/?lang_sel=en_UK) (PHPMyBibli) ([Wikipedia](https://en.wikipedia.org/wiki/PMB_%28software%29))? This is a free Integrated Library System written in PHP / SQL.

We could integrate PMB with RosarioSIS.
If you are interested, please contact us at https://www.rosariosis.org/services/

**Comment by francoisjacquet** [comment]
A new Library module is available for RosarioSIS at https://gitlab.com/francoisjacquet/Library

Cheers!
