### ISSUE TITLE
problem please help!!!!

### ISSUE THREAD

**Issue by aarassen** [francoisjacquet/rosariosis#170]

**Comment by francoisjacquet** [comment]
Hello @aarassen

Referring to your other issue #169 and your message in #23,
we can first deduce you are running an Ubuntu 16.04 server.
Please refer to the [installation directions](https://github.com/francoisjacquet/rosariosis/blob/mobile/INSTALL.md) specially written for Ubuntu.

Regarding the missing PHP `mbstring` & `xml` extensions installation on Ubuntu, a quick search would surely help:
https://duckduckgo.com/?q=ubuntu+16.04+install+php+xml+mbstring&t=ffsb&ia=qa

```
$ sudo apt-get install php-mbstring
$ sudo apt-get install php-xml
```

Next time please refer to the [new issue guidelines](https://github.com/francoisjacquet/rosariosis/blob/mobile/CONTRIBUTING.md).

We also remind you that we offer [email support](https://www.rosariosis.org/services/) for problems related to the installation of RosarioSIS.

**Comment by francoisjacquet** [comment]
Closed for inactivity.
