### ISSUE TITLE
Adding photos to users and students

### ISSUE THREAD

**Issue by imohamed2000** [francoisjacquet/rosariosis#171]
I have tried adding photos but they show like a broken image!!!
Any idea how it can be fixed?

Thanks
![page-shot-2016-12-1 student info general info](https://cloud.githubusercontent.com/assets/5850328/20782332/e20d23ac-b79b-11e6-8afc-e96075b55f2c.png)

**Comment by francoisjacquet** [comment]
Hello @imohamed2000 
Thank you for reporting the problem.
We could not reproduce the problem on our side (the JPG file did upload and is correctly displayed).

In order to help you, please refer to the [new issue guidelines](https://github.com/francoisjacquet/rosariosis/blob/mobile/CONTRIBUTING.md#new-issue).

**Comment by imohamed2000** [comment]
Thank you so much for replying.

I think it's permissions issue.

I tried to right click and view the image and got this error:

Forbidden

You don't have permission to access /assets/StudentPhotos/2016/1.jpg on this server.
Server unable to read htaccess file, denying access to be safe

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.

I checked the folder permissions and they are 755

Thanks

**Comment by imohamed2000** [comment]
I contacted the hosting and they sorted it. 

Thanks

**Comment by melroshamendra** [comment]
I try to add students images, but it not proceed black and white circle is continuously rotating 

![rs](https://user-images.githubusercontent.com/31309153/29661916-23a9a77c-88e3-11e7-9985-c83a0e3b9886.jpg)

**Comment by francoisjacquet** [comment]
Hello @melroshamendra 

Tahnk you for reporting the photo upload issue.

Please provide us with your exact configuration (OS, PHP & RosarioSIS versions, _diagnostic.php_ status...), and the corresponding Apache errors (see the _error.log_ file.)

**Comment by melroshamendra** [comment]
OS- windows 10 / Windows 7 
PHP - 5.4.45
RosarioSIS - version 3.4.2

**Comment by francoisjacquet** [comment]
OK thank you.

Some information is missing though. 
To really know what is going on, you can try again to upload the photo.
Then, open your _error.log_ file (should be situated in the Apache logs folder, under the folder where you installed Bitnami WAPP stack) and please copy / paste the last 20 lines.

**Comment by marozva** [comment]
Hi am facing the same issue when i try to up load a photo
checked my error.log file not showing errors
OS- windows 10 
PHP 5.6.31
RosarioSIS - Version 3.5
Wapp Stack 5.4.45-0
![image](https://user-images.githubusercontent.com/23170711/31311954-e484a3a6-abb7-11e7-9d52-b7d579483cd6.png)
Where am i wrong

**Comment by francoisjacquet** [comment]
@marozva thank you for the details and the screenshot.

Have you checked the _diagnostic.php_ page? Does it raise any configuration error?

Also, have you got any photo file inside the `2017` folder?

**Comment by francoisjacquet** [comment]
@marozva  The issue was due to a function relying on the PHP `exif` extension.

It has been fixed and will be available in the 3.5.2 [release](https://github.com/francoisjacquet/rosariosis/releases).

**Comment by marozva** [comment]
ok thank you

**Comment by marozva** [comment]
In reference to the new release 3.5.2 the pic is now uploading on creation of student and on updating  pic for a student who has already been created  but once you have already created a user on user (Teacher) and (Parent) before putting their pic on creation its failing to
update pic 

Regards

**Comment by marozva** [comment]
also on Parent (user)  the system is not uploading pics
