### ISSUE TITLE
Displaying "misleading update messages"

### ISSUE THREAD

**Issue by Abhinavram** [francoisjacquet/rosariosis#172]
I was trying to update the display picture of a school.

Apparently the file I uploaded was larger than the restricted size. Now this action has led to display of two messages.
1. Eventually it threw an exception saying  " Error: File size>2.0 MB".  (right behavior)
2. But along with the above message, it also displayed another message saying 
"Note: The school configuration has been modified"

Though, the first message is behaving as per the design - however, the second message might mislead the user's, hinting them a change in configuration.

![image](https://cloud.githubusercontent.com/assets/15023872/20911449/a14dfb44-bb2d-11e6-8b6b-d2f19fa4a824.png)

**Comment by francoisjacquet** [comment]
Hello @Abhinavram 

Thank you for sharing your experience.

The Note message will _always_ appear after the Save button as been pressed on the School Configuration page. The reason being there are **no easy means to check whether the user has actually** modified configuration values.

**Comment by francoisjacquet** [comment]
Closed for inactivity
