### ISSUE TITLE
"Logout -> back button -> reload", might cause a serious security threat to user's integrity

### ISSUE THREAD

**Issue by saishyamvinjamuri** [francoisjacquet/rosariosis#173]
Incidentally, after logging out in index.php page, I pressed back button and it redirected me to the below page,

![image](https://cloud.githubusercontent.com/assets/17414287/20911998/40112770-bb32-11e6-928c-7f2fc9638db2.png)

In the above page, it prompted me to reload. 

After reloading, surprisingly I landed back in the  Index page("https://www.rosariosis.org/demonstration/index.php") of the application. 

This might eventually be a big risk to user details.

**Comment by francoisjacquet** [comment]
Hello @saishyamvinjamuri 
Thank you for discovering and reporting this security issue.
The browser offers you to resend the credentials because the portal and the login form are sharing the same URL (`index.php`)
