### ISSUE TITLE
How can we attribute teachers to their students ?

### ISSUE THREAD

**Issue by jijonj** [francoisjacquet/rosariosis#179]
There is an option of attributing parents with their respective students but there is not for teachers or did I miss it. Help is appreciated

**Comment by francoisjacquet** [comment]
Hello @jijonj 

Parents can be directly associated to their children.
As for teachers, they are typically related to students through classes they teach (see _Scheduling > Courses_ to create courses and _Scheduling > Student Schedule_ to add a course to a student).

If you need support for RosarioSIS, please contact us directly at https://www.rosariosis.org/services/

**Comment by jijonj** [comment]
Thankyou Very much for your fast response. Information you provided solved my issue

**Comment by francoisjacquet** [comment]
You can now post your questions related to RosarioSIS use directly in the [forum](https://www.rosariosis.org/forum/).

The Github issues will be reserved for technical issues and errors.
