### ISSUE TITLE
Lenguaje Español.

### ISSUE THREAD

**Issue by Isa1027** [francoisjacquet/rosariosis#180]
Buen Día,

Disculpe, una pregunta ¿por que no me sale la los diferentes tipo de lenguaje;   español, frenaces, ingles? Lo tengo instalado de manera local.

De antemano muchas gracias. Excelente sistema.

**Comment by francoisjacquet** [comment]
Hello @Isa1027 

If you have followed the [How to install RosarioSIS on Windows](https://github.com/francoisjacquet/rosariosis/wiki/How-to-install-RosarioSIS-on-Windows) tutorial, you can add the French & Spanish languages this way:
Edit the `config.inc.php` file and add the locales:
```php
$RosarioLocales = array( 'en_US.utf8', 'fr_FR.utf8', 'es_ES.utf8' );
```

The Windows & cPanel tutorials have been updated to mention the `$RosarioLocales` config variable.

If you need more support, please contact us at https://www.rosariosis.org/services/
_Si necesita más ayuda, por favor contáctenos aquí: https://www.rosariosis.org/es/services/_

**Comment by Isa1027** [comment]
Buen Dia francoisjacquet.

Muchas Gracias por su ayuda.

Disculpe prodrias ayudar nuavamente explicándome por que me sale este error al insertar, alumnos e instituto.

**# " Failure Notice: DB Execute Failed."
"Additional Information:	ERROR: permission denied for sequence schools_seq"**




Cabe mencionar que el sistema ya lo tengo alojado en un host. La instalación la realice desde cpanel y al ejecutar el archivo diagnostic.php me muestra lo siguiente: 
#  **Your RosarioSIS installation is properly configured.**

Ojala me pueda ayudar y nuevamente muchas gracias.

**Comment by francoisjacquet** [comment]
https://github.com/francoisjacquet/rosariosis/issues?utf8=%E2%9C%93&q=is%3Aissue%20permission%20denied%20for%20sequence
