### ISSUE TITLE
Ability to assign multiple teachers to one course period.

### ISSUE THREAD

**Issue by dabest1** [francoisjacquet/rosariosis#181]
Hello,
I would like to ask for an enhancement to RosarioSIS. Would it be possible to add ability to assign multiple teachers to one course period? Our school has multiple teachers teaching in the same class room. Most of the time it is a teacher and teacher assistant. However, for bigger classes it is possible to have multiple teachers in one class room.

Thank you!

**Comment by francoisjacquet** [comment]
Hello @dabest1 ,

We have good news: the **Secondary Teacher** field is now available in the _Scheduling > Courses_ program.
Please upgrade to version 6.9.
