### ISSUE TITLE
School logo on pdf reports?

### ISSUE THREAD

**Issue by ianrogers1** [francoisjacquet/rosariosis#182]
Hello,
Is it possible to have our school logo appear on the printouts? class lists, class schedules, statements, attendance summaries, class pictures, etc. 
Many thanks,
I.Rogers

**Comment by francoisjacquet** [comment]
Hello @ianrogers1 

Yes, it is possible to have your school logo appear on Report Cards and Transcripts.
For other generated PDFs, you may consider modify the code or [contract us](https://rosariosis.org/services/) to do it for you.

**Comment by francoisjacquet** [comment]
Hello @ianrogers1 

I have good news.
The [PDF Header & Footer plugin](https://github.com/francoisjacquet/PDF_Header_Footer/) for RosarioSIS 3.4 will let you customize the PDF header and add the school logo to it.
