### ISSUE TITLE
Generar PDF

### ISSUE THREAD

**Issue by Isa1027** [francoisjacquet/rosariosis#183]
Buen Dia.

Disculpe, como puedo generar PDF si mi proyecto ya esta alojado en la web,  ya que cuando se instala en Windows se complementa con  **wkhtmltopdf** para generar PDF.

De antemano gracias por su comentario.
Saludos.

**Comment by francoisjacquet** [comment]
Hello @Isa1027 

To generate a PDF, you will need to install **wkhtmltopdf**.
If you cannot install it on your server, please check that [tip](https://rosariosis.org/tips-did-you-knows/#server-administrator) (in Spanish [here](https://rosariosis.org/es/tips-did-you-knows/#administrador-del-servidor)).

If you need help to install wkhtmltopdf or need professional hosting, [we can help you](https://rosariosis.org/services/). 
Consider writing in _English_ next time... or post on the [Spanish forum](https://rosariosis.org/forum/t/espanol).
