### ISSUE TITLE
Parse error: syntax error While configuring Moodle plugin

### ISSUE THREAD

**Issue by raghebalghezi** [francoisjacquet/rosariosis#185]
After following the tutorial for setting up Rosariosis- Moodle integrator, I am stuck on the last step (Moodle plugin configuration). Rosariosis shows the following syntax error:

`Parse error: syntax error, unexpected ')', expecting :: (T_PAAMAYIM_NEKUDOTAYIM) in /installation_path/plugins/Moodle/config.inc.php on line 145`

I checked config.inc.php file and did not find any double colons. Is this Rosariosis-related bug?

**Comment by francoisjacquet** [comment]
Hello @raghebalghezi 

Thank you for reporting the error. We could not reproduce it but were able to find references: http://stackoverflow.com/questions/18863625/parse-error-syntax-error-unexpected-expecting-t-paamayim-nekudotayim

The fix will come with version 3.1.2 that should be out for download later on today.
