### ISSUE TITLE
Showing period agains course on Calendar [Moodle]

### ISSUE THREAD

**Issue by kaustubhkabra** [francoisjacquet/rosariosis#186]
Thanks for such an awesome library. I read the documentation which mentions that only events and assignments will be displayed on calendar. Is there a way to display period associated against a course on Calendar for Students login ?

![image](https://cloud.githubusercontent.com/assets/642690/24722395/369794ca-1a61-11e7-9094-03a4029bc894.png)

**Comment by kaustubhkabra** [comment]
@francoisjacquet Can you please update here ? Your insights would help.

**Comment by francoisjacquet** [comment]
Hello @kk-code 

You would like the student's schedule (their course periods) to appear on their calendars, right?
It may be possible to enhance the Moodle plugin so to display course periods in Moodle's student calendar.

**Comment by francoisjacquet** [comment]
Closed for inactivity.

Please contact us at https://www.rosariosis.org/services/ if you would like to discuss this matter forward.
