### ISSUE TITLE
Android/iOS native support

### ISSUE THREAD

**Issue by kaustubhkabra** [francoisjacquet/rosariosis#187]
I understand and appreciate this repository being responsive. However, is there any module/extension available to make it work as an iOS/Android app out of the box ?
Thanks !

**Comment by francoisjacquet** [comment]
Hello @kk-code 

You can have RosarioSIS to work as an app in both Android and iOS using Safari or Chrome for Android's "Add to homescreen" menu.

This tip has been added to the [Tips & Did you Knows page](https://rosariosis.org/tips-did-you-knows/).
