### ISSUE TITLE
Error: Moodle: 404 - Unknown error When creating a new student in Moodle

### ISSUE THREAD

**Issue by raghebalghezi** [francoisjacquet/rosariosis#188]
When adding a new USER, Rosariosis signs it up on Moodle without any problems. However, when I tried adding a new STUDENT, Rosariosis adds it successfully to its database, but fails to add it to Moodle. It shows `Error: Moodle: 404 - Unknown error`. I have noticed that email field is missing in 'Add a Student' function, so although I used the 'common name' field as a replacement (from School Configuration), the error is still present.

**Comment by francoisjacquet** [comment]
Hello @raghebalghezi 

Thank you for reporting the error when adding a new student in Moodle from RosarioSIS.

Please enable the [debug mode](https://github.com/francoisjacquet/rosariosis/wiki/Moodle-integrator-setup#notes) in Moodle so you can send us a more specific error message.
