### ISSUE TITLE
Taking test online

### ISSUE THREAD

**Issue by matglas** [francoisjacquet/rosariosis#189]
Hi there,
Would it be possible to connect a online test to class and have a student take its test online?

**Comment by francoisjacquet** [comment]
Hello @matglas 

By "connect an online test", do you mean

- an external online test system (if yes which one?)
- or a RosarioSIS built-in test system that would come on top of the Assignments?

**Comment by matglas** [comment]
I mean option 2. I was looking into your system in comparison to populi http://www.populiweb.com/. We are investigating new options. One of the features that we use most there is the tests that can be taken online and results feed into the grading system directly.

**Comment by francoisjacquet** [comment]
OK thank you for the clarification.
It would be great to have an online test system integrated with the Gradebook.

We can develop it on your request. Please contact us at https://rosariosis.org/services/ if you decide to go with RosarioSIS.

**Comment by francoisjacquet** [comment]
A new Quiz module is available for RosarioSIS at https://gitlab.com/francoisjacquet/Quiz/

Cheers!
