### ISSUE TITLE
Many suggestions for changes in the source code

### ISSUE THREAD

**Issue by vanyog** [francoisjacquet/rosariosis#191]
Hello, François,

I announced in the forum I work on Bulgarian translation of RosarioSIS. Meanwhile I activated debug mode to see if there are any error or warning messages and all the time I encounter notices about missing variable initialization. I started to make corrections to remove these notices and made plenty of them. The progress of this work is seen in a fork of RosarioSIS repository  https://github.com/vanyog/rosariosis . You can find in this fork Bulgarian translation too. Please, have a look on corrections I make, and decide if you want to merge them to RosarioSIS project. If you prefer I can make a pull request or you can pull changes from my fork.

Best regards
Vanyo

**Comment by francoisjacquet** [comment]
Hello @vanyog 

Thank you for letting us know about your work.

Your pull request for the Bulgarian translation is much welcome.

Regarding the PHP notices fixes, I will surely merge them after having a closer look at it.

**Comment by francoisjacquet** [comment]
Hello @vanyog

Your Bulgarian translation (54% complete) was finally integrated in RosarioSIS 5.0: https://gitlab.com/francoisjacquet/rosariosis/blob/mobile/locale/REFERENCE.md

Another good news is I now work with `ROSARIO_DEBUG` mode activated and 90% of PHP notices were fixed :)

Thank you.
