### ISSUE TITLE
function CheckRequiredCustomFields always returns false

### ISSUE THREAD

**Issue by vanyog** [francoisjacquet/rosariosis#192]
It seems that function CheckRequiredCustomFields in /ProgramFunctions/Fields.fnc.php
always returns false. This is because you use an undefined variable: $category_id on line 739. As a result the SQL request on line 738 never succeed. I noticed that there is a control of if a field is required before the submission of data and data are always saved despite of the value returned by CheckRequiredCustomFields. The call of this functions becomes needless. Do you intend to stop to use CheckRequiredCustomFields in the future, or you think it will be better to fix the undefined variable bug in this function?

**Comment by francoisjacquet** [comment]
Hello @vanyog 

Thank you for reporting the error. The fix (`$category_id` var was removed) is available in version 3.3.2
