### ISSUE TITLE
 Allowed memory size exhausted fatal error when submitting vote to portal poll

### ISSUE THREAD

**Issue by vanyog** [francoisjacquet/rosariosis#193]
I created a very simple portal poll with 1 question in which 1 of 2 options must be selected. When a user click the Submit button an error occurs:

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32 bytes) in .../functions/Buttons.php on line 44

The file and line of code reported in the error message varies. This occurs on Mac - PHP 5.6 and Ubuntu - PHP 7.0 with the latest code from this repo.

**Comment by francoisjacquet** [comment]
Hello @vanyog 
Thank you for reporting the error.
The `button` function should not have been called in the AJAX vote case (not logged in), hence the infinite loop and memory error.
