### ISSUE TITLE
erro php extensions gettext

### ISSUE THREAD

**Issue by drengifoi** [francoisjacquet/rosariosis#194]
Hola, 
realice todo el procedimiento correcto y a la hora de abrir me sale pantalla blanca, reviso el diagnostic.php.  y me sale ERROR: PHP extensions: RosarioSIS relies in the gettext extension. please install and activate it

**Comment by francoisjacquet** [comment]
Hello @drengifoi 

Thank you for sharing your problem.

The error simply states the `gettext` PHP extension is not installed and should therefore be installed.
You can also check the **phpinfo** page and search for `gettext`.

Please post your specific server configuration and the steps / tutorial you followed to install RosarioSIS ([Ubuntu](https://github.com/francoisjacquet/rosariosis/blob/mobile/INSTALL.md), [Windows](https://github.com/francoisjacquet/rosariosis/wiki/How-to-install-RosarioSIS-on-Windows) or [cPanel](https://github.com/francoisjacquet/rosariosis/wiki/How-to-install-RosarioSIS-on-cPanel)?).

If you would like to write in Spanish, prefer the [Spanish forum / foro en español](https://www.rosariosis.org/forum/t/espanol).
