### ISSUE TITLE
Is there a way to change Rosario to Right to Left

### ISSUE THREAD

**Issue by abogadeer** [francoisjacquet/rosariosis#195]
Hi
I am planning to use rosario in my school. I need a right to left verion. DO you have a ready made one?
how can I change the alignment ? is there a style css file?

Thanks

**Comment by francoisjacquet** [comment]
Hello @abogadeer

The right to left direction is automatically set in RosarioSIS when the language is right to left (arabic, hebrew...).
Please tell us if you experience any issue with the theme styles (screenshot).

**Comment by abogadeer** [comment]
The main page needs to be corrected The column should be on the right not on the left

https://ibb.co/jokzkF

**Comment by francoisjacquet** [comment]
Hello @abogadeer 

Thank you for your comment about the menu. It is now on the right side of the screen.

The Arabic translation has been updated too thanks to you.
You can preview the changes on the [demo site](https://rosariosis.org/demo/).
They will be available in the 3.4.2 release.

**Comment by abogadeer** [comment]
Now it looks great in Arabic.
