### ISSUE TITLE
Security enhancement: Session timeout if idle for 20 minutes

### ISSUE THREAD

**Issue by dpredster** [francoisjacquet/rosariosis#196]
Hi François,

I have integrated jquery session timeout to RosarioSIS 3.4. This prompts the user that they would be logged out if they have been inactive for more than 20 minutes. After 2 minutes if there is no user intervention it logs them out.

If you think this may be useful to the project please feel free to mere the changes.

Regards,
dpredster

**Comment by francoisjacquet** [comment]
Hello @dpredster
Thank you for sharing your enhancement.
I've had a look at it and left you some technical comments (although I did not test it yet).

As for now, RosarioSIS will log you out according to the php.ini https://stackoverflow.com/questions/8311320/how-to-change-the-session-timeout-in-php#8311400

This may be longer or shorter than 20 minutes of inactivity and is configured by server administrator.
For example, I like the fact that I can keep my session open (and inactive) for hours on my personal dev server.

Now, letting the user know his session will expire soon and ask him whether he would like to keep it open is _good practise_.

A similar solution taking in account the PHP  session timeout setting would be great (dynamically setting the timeout (now statically set to 20min) using `ini_get( 'session.gc_maxlifetime' )`).

**Comment by dpredster** [comment]
Hi François,

Thank you for you technical comments. I reviewed them and made the changes as necessary.

The idle session timeout is part of the security settings I have been working on. The complete security settings allows for the timeout to be dynamic. In these settings if No. of minutes of inactivity before user is automatically logged out is set to 0 the user would not be logged out. This is currently in the beta stage. It is functional however I need to clean up the code a bit. I would upload it to github when it is complete.

![security_settings](https://user-images.githubusercontent.com/3442375/28139435-4072b8f4-6722-11e7-9f18-a931897040a9.png)

I would take a look at PHP session timeout and see how I can integrate it.

Thank you again for your help. I have been able to learn quite a lot from you and your project.

**Comment by francoisjacquet** [comment]
Hello @dpredster 

Any update on the JS automatic logout feature?

**Comment by dpredster** [comment]
Hi @francoisjacquet 

I have been a bit busy with some other projects. I have been testing the security settings for a while and it seems to be working well. I will pots the code to github in a day or two.

I'll let you know when I do.

**Comment by dpredster** [comment]
Hi @francoisjacquet 

I have posted the automatic logout and other security changes that are shown in the above screen shot to my github page. You can check it out. 

The automatic logout feature includes a popup that  warns the user that they are about to be logged and gives them one minute to either stay connect of logout. If the user does not respond within that time frame it logs out in any open tabs within the browser. 

Due to the user needing to refresh the page after any changes to the Security Settings in order for it to take effect, I have included a script to refresh the page after 5 seconds.

**Comment by francoisjacquet** [comment]
Hello @dpredster 

Thank you for sharing those extra security features.

I have reviewed the [code](https://github.com/dpredster/rosariosis/commit/4c02328608e160730fd5e74871fda8998b0ebcfa) and have 2 general remarks:
1. Many extra CSS ([2](https://github.com/dpredster/rosariosis/commit/4c02328608e160730fd5e74871fda8998b0ebcfa#diff-35b4a816e0441e6a375cd925af50752cR101)) and JS ([4](https://github.com/dpredster/rosariosis/commit/4c02328608e160730fd5e74871fda8998b0ebcfa#diff-35b4a816e0441e6a375cd925af50752cR60)) files were added to core.
2. The security features do not come in an independent module.

Regarding point 1., having to raise the initial JS & CSS payload by more than 4x and 2x respectively is not to be considered lightly.

Therefore, regarding point 2., I have added 2 new **hooks / actions** to let you add the JS and CSS dependencies where needed (page header or footer), right from the `functions.php` file of an extra module.

Another remark: the Security options could be directly added to the `CONFIG` DB table.

**Comment by francoisjacquet** [comment]
Please note that the "Failed Login Attempts Limit" and "Password Strength" config options were added to RosarioSIS since version 4.4.

![image](https://user-images.githubusercontent.com/4723501/72103954-946c7400-332a-11ea-9202-4d4c078428e3.png)

Closing the issue.
