### ISSUE TITLE
student can't login

### ISSUE THREAD

**Issue by katika** [francoisjacquet/rosariosis#198]
I'm running RosarioSIS 3.4 on debian 8.6, php 5.6.30 and mariadb 10.0.30 ; but studends created can't login. It's said in logs that thoses students usernames doesn't exist. Any help?

**Comment by katika** [comment]
following the same rules, users can login, but not students. Does student username's follow a particular rule?

**Comment by francoisjacquet** [comment]
Hello @katika,

Thank you for reporting the issue.

Please give the exact steps to reproduce your issue where students can't login.

Thank you,
François

**Comment by katika** [comment]
![selection_113](https://user-images.githubusercontent.com/29801120/28313593-5afa31de-6baf-11e7-9588-967f05b49057.png)
In the username field, i tried many variations: o.mbanga, m.owona, owona.

Here's the login error message:
![selection_114](https://user-images.githubusercontent.com/29801120/28313791-0a93a27e-6bb0-11e7-9fc6-aa988bd21c96.png)

Worth to mention that default student "Student" don't have this issue.

Thanks

**Comment by francoisjacquet** [comment]
Hello @katika 

Thank you for the screenshots.

This is because the enrollment date is set to the **12 of September**.
The student account is **inactive** as of today and thus cannot login.
We will try to add a more explicit error message on the login screen.

**Comment by katika** [comment]
Thanks @francoisjacquet . After all it's rather obvious. Thanks again

**Comment by francoisjacquet** [comment]
Hello @katika 
The error message "Your account has not yet been activated." is displayed in case the student is inactive (attendance start date > today).

![screenshot from 2017-07-31 15-22-51](https://user-images.githubusercontent.com/4723501/28779725-70a97de6-7604-11e7-8234-d89c6b0387cd.png)

You can preview it in the [demo](https://www.rosariosis.org/demo/).
