### ISSUE TITLE
adding captcha to registration and login

### ISSUE THREAD

**Issue by abogadeer** [francoisjacquet/rosariosis#199]
I have searched the settings in Rosario and did not find any captcha

Students are nasty and they might try to do things that might cause issues to the server. 

Can you add Captcha Confirmation to login and registration?

**Comment by francoisjacquet** [comment]
Hello @abogadeer

I am not sure whether students are nasty or not, but one thing is sure, bots are :)
The good news is captcha are made for bots, not students.

We can add some sort of ban on the login screen in case of abuse, configurable from the _Access Log_ program maybe.
As for the new account forms, some sort of captcha can be implemented in a future version too.

If you would like to have it in the next release, you can sponsor those enhancements at https://www.rosariosis.org/services/

**Comment by francoisjacquet** [comment]
![screenshot from 2017-08-25 22-33-46](https://user-images.githubusercontent.com/4723501/29731690-ad6e5e28-89e5-11e7-99a6-43a8b1594efa.png)

@abogadeer thank you for your sponsoring.

The failed login ban feature is out, including help and Spanish + French translations!
Check it out at https://www.rosariosis.org/demo/

**Comment by francoisjacquet** [comment]
Hello @abogadeer 

The captcha has been added to the Create User / Student Account forms.
![screenshot from 2017-08-26 18-01-10](https://user-images.githubusercontent.com/4723501/29742974-caf32228-8a88-11e7-82a7-c67ef1e58b2a.png)

You can still preview it on the demo site at https://www.rosariosis.org/demo/

Let us know if you experience any problem with captchas or the login ban system.

**Comment by abogadeer** [comment]
hi


I will check it tomorrow

and get back to you

-- 
لست بحاجة إلى سبب كي تساعد الآخرين

You don't need a reason to help others

**Comment by abogadeer** [comment]
this is exactly what I wanted

thank you so much


one more thing

There is no way to delete a student with all his/her data.
Is there?

if not, can you add that feature?

I made a deadly mistake by adding elementary students to a secondary school
