### ISSUE TITLE
Deleting student record (feature request)

### ISSUE THREAD

**Issue by abogadeer** [francoisjacquet/rosariosis#201]
I have a long list of students which I imported from the import module to the wrong school. I need to delete them and I could not. 

The feature as far as I can tell that the feature does not exist. 

Could you please add it?
If there is no workaround.

Thanks

**Comment by francoisjacquet** [comment]
Hello @abogadeer 

Deleting a student is problematic. If you remove a student that is not enrolled anymore, the
data will not be available if he enrolls again later, or if an exterior institution need
information about this student, like certificates.
Simply terminate the enrollment (see the Enrollment _Dropped_ date) and RosarioSIS will
occult the student until you need him. Then, the student will be accessible when you check
_Include Inactive Students_.

You will find information about this and more tips in the [Helpful Tips PDF](https://rosariosis.org/tips-did-you-knows/#administrator).

**Comment by francoisjacquet** [comment]
@abogadeer 

Thank you for sponsoring the feature development.

The "Delete" button will be useful for Students who have been created by mistake.

It will show up **only if they have no associated Grades, Attendance or Schedule records**.

![screenshot from 2017-09-03 21-12-02](https://user-images.githubusercontent.com/4723501/30005901-ccfb66c4-90ec-11e7-9086-3e3d5e734a63.png)
