### ISSUE TITLE
user import (feature request)

### ISSUE THREAD

**Issue by abogadeer** [francoisjacquet/rosariosis#203]
Hi

can you add to the student import a section where I can choose the type of account I am creating?

I need to import students and their parents.

Thanks

**Comment by francoisjacquet** [comment]
Hello @abogadeer 

Thank you for sharing your enhancement idea.

Did you know you can already import students and their parents using the [Students Import Premium module](https://www.rosariosis.org/students-import-module/)?

Parents will be added as contacts (see the _Student Info_ program _Contacts & Addresses_ tab).

Contacts can later be created as actual Parent users and have their account using the _Create Parents_ program.

This process may be a bit tedious and you may want to directly create Parent users. A **Parents and Staff Import** module can developed to this effect.

Please [contact us](https://www.rosariosis.org/services/) if you wish to sponsor the development.

**Comment by abogadeer** [comment]
@francoisjacquet 
I have no problem sponsoring the development of the module

**Comment by francoisjacquet** [comment]
Hello @abogadeer 

The new _Staff and Parents Import_ module is out:
https://github.com/francoisjacquet/Staff_Parents_Import/

You can test it on the demo site: https://www.rosariosis.org/demo/

Thank you for sponsoring the development!

**Comment by abogadeer** [comment]
I added 3 users to the demo site 

works great

thanks
