### ISSUE TITLE
config relation doesn't exist error

### ISSUE THREAD

**Issue by agomezgar** [francoisjacquet/rosariosis#204]
Hi, great work.
I was testing your software in my server, but I get the message "the config relation doesn't exist". I have an Ubuntu 16.04 server with php 7.0. Can this version be my real problem?.

Thanks for your time.

**Comment by lkozloff** [comment]
I'm running 16.04 with PHP 7.0 and it's working for me. `The config relation doesn't exist` is an error coming from Postgres.

Perhaps you created the database, but didn't load the intial configuration?

**Comment by agomezgar** [comment]
Thanks for your response. I'll check it out.

**Comment by francoisjacquet** [comment]
Hello @agomezgar 

Thank you @lkozloff for pointing the error is related to the database, not PHP.

For PHP7 concern, please see #163

The `config relation doesn't exist` error means RosarioSIS cannot find the `config` table in the database you have specified in the `config.inc.php` file.

Please read the installation instructions again. (You need to both create the database **and** import the `rosariosis.sql` file.)

**Comment by francoisjacquet** [comment]
You can also check https://github.com/francoisjacquet/rosariosis/wiki/How-to-install-RosarioSIS-on-cPanel#enter-rosariosis 

The `config relation doesn't exist` error may also happen when your PostgreSQL user has not been added to the database.
