### ISSUE TITLE
How do i add subjects taken by a student in a class 

### ISSUE THREAD

**Issue by marozva** [francoisjacquet/rosariosis#205]
How do i add subjects taken by a student in a class  to the student account and also how i do allocate a subject to teacher for instance Student A doing Maths Subject and the Teacher being Mr B

**Comment by francoisjacquet** [comment]
Hello @marozva 

Have you generated and read the Administrator Handbook / User manual PDF?

Please head to the [Quick Setup Guide](https://rosariosis.org/quick-setup-guide/) for instructions on how to generate handbooks and configure RosarioSIS.

**Comment by marozva** [comment]
thank you that skipped me ...
