### ISSUE TITLE
Warning: Teachers have missing attendance data. shows up when I add courses

### ISSUE THREAD

**Issue by abogadeer** [francoisjacquet/rosariosis#206]
Hi

I added one course period and I did **not** add any student to it.

When I login, I get: Warning: Teachers have missing attendance data

Is this normal? 
should rosario behave this way?

**Comment by francoisjacquet** [comment]
Hello @abogadeer 

Thank you for reporting this behavior.

The warning should not appear unless students are actually enrolled in the course period.

A link for Teachers or Admins that will take them to the right page to directly take attendance for the Course Period can be added.
