### ISSUE TITLE
Payment increases balance and assigning Salary decrease balance

### ISSUE THREAD

**Issue by jijonj** [francoisjacquet/rosariosis#207]
Sorry for writing this issue. I didn't recognize what CR meant

**Comment by jijonj** [comment]
Sorry for writing this issue.

**Comment by francoisjacquet** [comment]
When _CR_ is displayed next to the balance amount, it means _Credit_.

This may not be obvious to everybody. Suggestions are welcome.

**Comment by jijonj** [comment]
CR is fine. I mean that's all you could write the really. Thanks.
