### ISSUE TITLE
Cannot add salary to a teacher after 250 salaries

### ISSUE THREAD

**Issue by jijonj** [francoisjacquet/rosariosis#208]
I wonder if there is a limit to the salaries table or something excuse my low technical knowledge

**Comment by francoisjacquet** [comment]
Hello @jijonj

Thank you for reporting this issue with the salaries.

There is no hard limit set to the number of salaries.

Please adjoin a screenshot and any detail (including your server/client configuration and versions) and steps that can help reproduce the issue.

Does the teacher user still exist? Did you upgrade RosarioSIS or did you proceed to rollover recently? Is there anything different you have noticed from back when salaries were properly saved?

Thank you.

**Comment by jijonj** [comment]
Hi
Thank-you for the quick response.

The teacher user still exist, I did a roll over recently.
I also checked with a new installation of the latest rosariosis.

The one thing i could notice is that after 250 salaries new entries are not getting added to the salaries, you can check it from your end because i have checked it twice and its not exceeding the limit of 250.

Ubuntu 16.04.2 LTS (GNU/Linux 4.8.0-54-generic x86_64)
Server version: Apache/2.4.18 (Ubuntu)
psql (PostgreSQL) 9.5.8
Tried with RosarioSIS Student Information System 3.5.1 and 3.5.2

**Comment by francoisjacquet** [comment]
Hello @jijonj 

Do you mean when you try to add a salary to a _same_ teacher who already has got 250 salaries?

![screenshot from 2017-11-01 21-44-15](https://user-images.githubusercontent.com/4723501/32297001-0714787a-bf4e-11e7-9704-2debd0cd5ae5.png)

Here we can see each salary line adds up 4 input fields that will be sent when submitting the form.
250 salaries would total **1000 input fileds**.

When dealing with long lists having those inputs, you are reaching PHP's [max_input_vars](http://php.net/manual/en/info.configuration.php#ini.max-input-vars) setting.
This value can be raised in your `php.ini` config file (limited to **1000** by default).

Now, can we consider having more than 250 salaries for the same person per school year to be an edge case?

**Comment by jijonj** [comment]
Thanks for solving the issue
It was the max_input_vars limit in php.ini
Thanks again
