### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by rsulejmani** [francoisjacquet/rosariosis#210]
When ever I try to add a Course or anything this pop ups and doesn't add it for me.
Here is a screenshot of the problem. 
![screenshot_42](https://user-images.githubusercontent.com/15115677/31888007-04354854-b7c0-11e7-8e07-4fd1adf736c9.png)

**Comment by francoisjacquet** [comment]
Hello @rsulejmani 

Thank you for the screenshot.

Please refer to other issues (and their solutions) related to DB permission denied errors:


https://github.com/francoisjacquet/rosariosis/issues?utf8=%E2%9C%93&q=is%3Aissue%20permission%20denied%20
