### ISSUE TITLE
student import and staff import with RTL 

### ISSUE THREAD

**Issue by abogadeer** [francoisjacquet/rosariosis#211]
WHen using these imports in English Language, everything works fine, but when I switch to Arabic which is RTL language, I get this strage shif of column to the left where I can see almost nothing

The picture says it all and I can replicate it on the demo site
![untitled](https://user-images.githubusercontent.com/29820341/32391388-f1570f98-c0e2-11e7-893d-ead56693d04a.png)

**Comment by francoisjacquet** [comment]
I believe this was fixed by switching from Chosen to Select2 in version 10.7
