### ISSUE TITLE
To put RosarioSIS in french

### ISSUE THREAD

**Issue by Tiadroh** [francoisjacquet/rosariosis#212]
Hello,
I installed RosarioSIS 3.5.2 by following this https://github.com/francoisjacquet/rosariosis/wiki/How-to-install-RosarioSIS-on-Windows
in my configuration I used:
wampserver3.1.0_x86 with Apache / 2.4.27 (Win32) PHP / 7.1.9
phpPgAdmin-5.1
postgresql-10.0-2-windows
In my config.inc.php configuration file
I have this

// Optional: activate other languages; here, for Spanish & French:
   $ RosarioLocales = array ('en_US.utf8', 'es_ES.utf8', 'fr_FR.utf8');
   
   
So far everything is working well.
My problem is at the language level, I can not put in French.
I read this https://github.com/francoisjacquet/rosariosis/wiki/Localizing,-translate-RosarioSIS-with-Poedit
and this https://github.com/francoisjacquet/rosariosis/blob/master/locale/README

Since it is GetText PHP that is used, I enabled extension extension = php_gettext.dll
in php.ini (from php and apache) but nothing has changed.

**Comment by abogadeer** [comment]
$ RosarioLocales = array ('en_US.utf8', 'es_ES.utf8', 'en_FR.utf8');

it should be
$ RosarioLocales = array ('en_US.utf8', 'es_ES.utf8', 'fr_FR.utf8');

**Comment by Tiadroh** [comment]
hi abogadeer, 
sorry it's a mistake but the problem remains the same with
 // Optional: activate other languages; here, for Spanish & French:
$ RosarioLocales = array ('en_US.utf8', 'es_ES.utf8', 'en_FR.utf8');

**Comment by Tiadroh** [comment]
hi abogadeer,
sorry it's a mistake but the problem remains the same with
// Optional: activate other languages; here, for Spanish & French:
$ RosarioLocales = array ('en_US.utf8', 'es_ES.utf8', 'fr_FR.utf8');

**Comment by francoisjacquet** [comment]
Hello @Tiadroh

Thank you for reporting the issue and communicating details about your configuration.

Good to know the issue with gettext has not been fixed yet on Window$!

The tutorial you mention advise you to install the WAPP stack with PHP **5.4** for this same issue regarding gettext.

If you want to have more details about this issue, please search old issues mentioning gettext and Window$: https://github.com/francoisjacquet/rosariosis/issues?utf8=%E2%9C%93&q=is%3Aissue%20gettext%20windows
