### ISSUE TITLE
local timing choice

### ISSUE THREAD

**Issue by abogadeer** [francoisjacquet/rosariosis#213]
Hi
we faced an issue with Rosario with local time. Our local time is +3 gmt and the time in rosario seems to be different. It was almost 11 am today until the date was changed from 14-11-2017 to 15th. Teachers got annoyed because they needed to change the date to the 15th so they can take the attendance.

Is there a way to force Rosario to use the local timing or any other specific time?

**Comment by francoisjacquet** [comment]
Hello @abogadeer

You can set your timezone in the `config.inc.php` file. Please refer to the optional variables section of the [INSTALL.md file](https://github.com/francoisjacquet/rosariosis/blob/mobile/INSTALL.md#optional-variables)

**Comment by abogadeer** [comment]
is this the right code?

$Timezone = 'Asia/Riyadh';

**Comment by francoisjacquet** [comment]
Yes, `Asia/Riyadh` is a recognized timezone and `$Timezone = 'Asia/Riyadh';` is the correct PHP code to set this timezone.
