### ISSUE TITLE
RTL isses

### ISSUE THREAD

**Issue by abogadeer** [francoisjacquet/rosariosis#214]
Hi
I noticed three issues when using Arabic which is RTL

1- When adding courses 
![courses](https://user-images.githubusercontent.com/29820341/33185904-d8a9e3f8-d096-11e7-8f7e-7ca29b233138.png)

2- after entering grades for a certain homework
![grades of homework](https://user-images.githubusercontent.com/29820341/33185919-e9e57ca4-d096-11e7-8113-f8d213876a33.png)

3- when trying to print the grades of a certain homework
![printable page grades](https://user-images.githubusercontent.com/29820341/33185929-fca98628-d096-11e7-94ba-e0f35fef73a3.png)

in the printable page, everything seems to be aligned to left not right. The grades are in bad shape. They are not clear. The first one should be 10/5  but it is show 510.

I will report more issues as I use the system
Thank you for your effort

**Comment by francoisjacquet** [comment]
Hello @abogadeer 

Thank you for reporting those RTL layout issues.

**Comment by abogadeer** [comment]
Hello @francoisjacquet 
Add to the list above the attendance page.

The page where a teacher takes attendace

**Comment by abogadeer** [comment]
The messaging module has similar issues 
![messaging 1](https://user-images.githubusercontent.com/29820341/33443496-c8e6ddb4-d608-11e7-959e-3f09eac92074.png)

**Comment by abogadeer** [comment]
add to the list the following
Advanced reports. 
All reports displayed when I choose the print option have RTL issues
![advanced reports rtl issue](https://user-images.githubusercontent.com/29820341/34261145-489761ca-e679-11e7-9120-6031d75c6555.jpg)

The enrollment info which is displayed at the bottom of the page
![enrollment at the bottom of the page rtl issue](https://user-images.githubusercontent.com/29820341/34261176-636c5d0c-e679-11e7-9f0b-7bffd94a6923.jpg)

missing attendance notification at home page has an issue
![missing attendance rtl issue](https://user-images.githubusercontent.com/29820341/34261196-74990238-e679-11e7-9697-45637221d885.jpg)

the schedule has also an issue
![print timetable rtl issue](https://user-images.githubusercontent.com/29820341/34261225-8aa314d8-e679-11e7-8f9d-4aedce136d81.jpg)

students' lists in any location has issues with RTL alignment
![student list rtl issue](https://user-images.githubusercontent.com/29820341/34261246-9c6624da-e679-11e7-8c35-6b5ed1abc14d.jpg)

**Comment by abogadeer** [comment]
It seems everything works fine

Thanks a lot and Merry Christmas

**Comment by francoisjacquet** [comment]
Hello @abogadeer 

Thank you for sponsoring the RTL layout fixes.
They will ship this week with RosarioSIS 3.7.

Feel free to reopen the issue (or create a new one) if you spot more of them.
