### ISSUE TITLE
Error: RosarioSIS cannot connect to the PostgreSQL database.

### ISSUE THREAD

**Issue by ACANCAM** [francoisjacquet/rosariosis#217]
Hello Françoise:

I have started again installing the new version of RosarioSIS 3.5.3 from the beginning, not updating it, in a new virtual machine in Google Cloud.

The problem was that, although apparently connected to the database (the data was saved), when opening the diagnostic.php file appeared the following message:

"Error: RosarioSIS can not connect to the PostgreSQL database." Either Postgres is not running, it was not started with the -i option, or connections from this host are not allowed in the pg_hba.conf file.

So I started again installing everything from the beginning with the new version 3.5.3 and the error reappears

In the installation instructions you talk about modifying the file pg_hba.conf but I do not know what I have to write exactly. Could you help me please?

My configuration is:
VM on Google Cloud Platform
Rosariosis 3.5.3
Ubuntu 14.04 with Apache 2.4.18, Postgres 9.3.10 and PHP 5.5.9

Thank you very much

**Comment by francoisjacquet** [comment]
Hello @ACANCAM

Please search old issues before opening a new one.

This problem has already been addressed:
https://github.com/francoisjacquet/rosariosis/issues?utf8=%E2%9C%93&q=is%3Aissue+connect+postgresql+database

It is worth mentioning installation problems shown on the `diagnostic.php` page are not RosarioSIS issues.

Finally, for server and RosarioSIS configuration problems we offer email support or even full installation services at https://www.rosariosis.org/services/

**Comment by muse-sisay** [comment]
For anyone looking for a solution refer to my https://github.com/francoisjacquet/rosariosis/issues/220#issuecomment-940214256
