### ISSUE TITLE
Names display 

### ISSUE THREAD

**Issue by abogadeer** [francoisjacquet/rosariosis#218]
hi 
Is there a way to change how names of students, staff and users are displayed?

In Arabic the way we write names is a bit different

**First - Middle - Last**

First - Middle - Last
All of our names lists follow that pattern.
Can you add an option so we can change the naming system?

Thanks

**Comment by francoisjacquet** [comment]
Hello @abogadeer,

Thank you for sharing this enhancement idea.

We could add that name pattern to the _School Configuration_ (or per user _Preferences_?) options, and use it everywhere student / user names are displayed.

If you will sponsor the development, please contact us at https://www.rosariosis.org/services/

**Comment by francoisjacquet** [comment]
Hello @abogadeer,

Thank you for sponsoring this enhancement.

You can now set the _Display Name_ format in the _School Configuration_ program:
![screenshot from 2018-01-14 17-26-46](https://user-images.githubusercontent.com/4723501/34918266-eee5277a-f947-11e7-9149-a23205a0fd87.png)

You can preview it on the [demo site](https://www.rosariosis.org/demo).

This will be released as beta (v3.7-beta) as this modifies most programs and needs proper testing.

**Comment by abogadeer** [comment]
excellent work.

do not forget to read your email (;
