### ISSUE TITLE
Error modifying user permissions. 

### ISSUE THREAD

**Issue by ACANCAM** [francoisjacquet/rosariosis#219]
Hi François:

When I modify the user permissions of parents and teachers, so that they can edit the fields of general information or any other field that I have created, it has no effect. Parents and teachers can see these fields but can not modify them, even if they have been given permission to edit. What is the problem?

Best regards

**Comment by francoisjacquet** [comment]
Hello @ACANCAM 

Thank you for reporting the issue.

Yes, this feature has not been implemented yet, mainly for security concerns.

Yet, users _should_ be able to edit info when given permission and access.

**Comment by ACANCAM** [comment]
Ok Thank you very much. I will be pending to install the improvement as soon as it is available.

By the way, the email configuration improvement is great. Much easier to install now.

Best regard

**Comment by francoisjacquet** [comment]
Hello @ACANCAM 

Teacher & Parent users can now Edit User Info.

Check version 4.9.1: https://gitlab.com/francoisjacquet/rosariosis/-/tags
