### ISSUE TITLE
Could not Connect to Database Server 'localhost'. 

### ISSUE THREAD

**Issue by mustfullDev** [francoisjacquet/rosariosis#220]
Hi,
I follow all installation directions for Windows and when i try to Access RosarioSIS at http://127.0.0.1/rosariosis/  it show me that message :
"

We have a problem, please contact technical support ... 

Date: 01/05/2018 07:34:48
 
Failure Notice: Could not Connect to Database Server 'localhost'.
 
Additional Information: 
 
"

**Comment by francoisjacquet** [comment]
Hello @mustfullDev

Thank you for reporting your issue and sharing your configuration.

This database connection issue has already been adressed. Please search old issues before opening a duplicate: https://github.com/francoisjacquet/rosariosis/issues?utf8=%E2%9C%93&q=is%3Aissue+connect+database+server

**Comment by francoisjacquet** [comment]
Closed for inactivity.

**Comment by muse-sisay** [comment]
I know this is a dead thread but for anyone else who is getting the same error, it took a very long time to figure it out , here is the solution that worked for me.

I made a backup copy of `vim /var/lib/pgsql/data/pg_hba.conf` and then replaced it [with the following](https://gist.github.com/francoisjacquet/9570899). 
```
# DO NOT DISABLE!
# If you change this first entry you will need to make sure that the
# database superuser can access the database using some other method.
# Noninteractive access to all databases is required during automatic
# maintenance (custom daily cronjobs, replication, and similar tasks).
#
# Database administrative login by Unix domain socket
local   all             postgres                                peer

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     md5
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
# Allow replication connections from localhost, by a user with the
# replication privilege.
#local   replication     postgres                                peer
#host    replication     postgres        127.0.0.1/32            md5
#host    replication     postgres        ::1/128                 md5
```

Then restart the service 
```console
systemctl restart postgresql.service
```

That is what it took. Such a simple solution. Unfortunately I can't give you a reason why this worked.[Here](https://github.com/francoisjacquet/rosariosis/issues/21) #21  is the GitHub issue where I found the answer.

Good Luck !!
