### ISSUE TITLE
Deleting a student Contact Information deletes the student

### ISSUE THREAD

**Issue by ssreyah** [francoisjacquet/rosariosis#221]
On RosarioSIS v3.6.1, deleting a student Contact Information leads to a prompt "Are you sure you want to Delete that Student?". If you click "OK' the student is deleted.

**Expected Behavior**
Only the Contact Information is deleted.

**Steps to reproduce**

- Log in to the demo site at https://www.rosariosis.org/demonstration
- Log in as administrator/administrator
- Select a student record (Students->Find, then choose a student)
- Browse to Addresses & Contacts tab, then add a Contact Information & an Address
- Click the " - " to delete the recently added Contact Information or Address
- Observe that the dialog prompts you to delete the student.

**Comment by francoisjacquet** [comment]
Hello @ssreyah 

Thank you for reporting this issue when deleting student Address or Contact information.

It has been fixed and will ship with RosarioSIS 3.7.
