### ISSUE TITLE
Suggestion: Hovering mouse over student name shows student photo

### ISSUE THREAD

**Issue by ssreyah** [francoisjacquet/rosariosis#222]
My admins noticed that when teachers take attendance, they can see student photos just by hovering mouse over a student. That is not the case for normal student lists.

For admins and nurse, they don't usually remember the student faces so it would be helpful to quickly see student faces just by scrolling through.

**Comment by francoisjacquet** [comment]
Hello @ssreyah 

Thank you for sharing your suggestion.

Having student photos when hovering student names is a great feature for staff.

Currently, only a few chosen lists like the _Take Attendance_ one have it.
We can think of adding photos to every _Expanded View_ list by default:
![image](https://user-images.githubusercontent.com/4723501/35216753-fcf98c08-ff68-11e7-86a2-3642939f4f40.png)

If you want to sponsor this enhancement, contact us at https://www.rosariosis.org/services/

**Comment by francoisjacquet** [comment]
Hello @ssreyah

We have good news!

Photo tip messages appear when hovering names. This is now activated in v3.8 for **advanced** view listings (both students and users).

**Comment by ssreyah** [comment]
Hello @francoisjacquet ,
This is amazing. You are awesome :+1:
