### ISSUE TITLE
missing attendance notifications of first semester appear in second

### ISSUE THREAD

**Issue by abogadeer** [francoisjacquet/rosariosis#224]
Hi @francoisjacquet 

today is our first day in semester 2 and we have missing attendance data from semester 1. Is this how Rosario should behave? Should not the notifications of missing attendance data disappear when I choose semester 2?

**Comment by abogadeer** [comment]
course periods of semester 1 should not appear in semester 2

that is what I think

**Comment by francoisjacquet** [comment]
Hello @abogadeer 

Yes, this is how RosarioSIS should behave. The missing attendance data is displayed on the portal for every school and every marking period in the current school year.
