### ISSUE TITLE
Gradebook Grade Student Photos won't disappear

### ISSUE THREAD

**Issue by ssreyah** [francoisjacquet/rosariosis#226]
On Current RosarioSIS 3.7, When you go to Grades > Gradebook Grades, then choose a teacher name, a list of students will appear. Hovering mouse over each student names will show the corresponding student's photo. After clicking on the student's name, the photo will follow the cursor until refresh.

**Expected Behavior**
After clicking on student's name, the student photo would disappear. 

**Steps to reproduce**

- Log in to the demo site at https://www.rosariosis.org/demonstration
- Log in as administrator/administrator
- Go to Grades > Gradebook Grades > Search and Select a Teacher
- A student list appear (Make sure the student has a photo)
- Hover mouse over student's name -> Student photo popup next to cursor
- If you click on it and not move the cursor, the student photo will follow the cursor even the working student and teacher were cleared (If you click and move the cursor quickly before the new page is loaded, there's no problem but that's not the common case)

**Comment by francoisjacquet** [comment]
Hello @ssreyah 

Thank you for reporting this display bug related to the student photo tooltip.

I was able to reproduce it with Chromium / Chrome browser (no issue on Firefox). The fix will come in the 3.7.1 release.

**Comment by ssreyah** [comment]
Thank you @francoisjacquet :+1:
