### ISSUE TITLE
Transferir Periodos

### ISSUE THREAD

**Issue by NicolasRua** [francoisjacquet/rosariosis#229]
Hola, 

Mi pregunta esta orientada sobre un error a la hora de hacer la transferencia de periodos, ERROR: permission denied for sequence marking_period_seq.   Los permisos estan dados en la base de datos, pero persiste el error.

Les agradezco la colaboración.

**Comment by francoisjacquet** [comment]
Hello @NicolasRua,

The sequence error is a DB installation related issue and has already been adressed.
Please search old issues before opening a new one:
https://github.com/francoisjacquet/rosariosis/issues?utf8=%E2%9C%93&q=is%3Aissue+error+permission+denied+for+sequence
