### ISSUE TITLE
RosarioSIS cannot connect to the Postgres database

### ISSUE THREAD

**Issue by azwanmuslim** [francoisjacquet/rosariosis#23]
![screenshot066](https://f.cloud.github.com/assets/6987831/2448590/31d604f8-aea8-11e3-8606-dbbc4b6a7709.jpg)
hi

i install php and postgresql using bitnami apps

i already configure the database and all, but when i try to launch the rosariosis, nothing happen

when i run the diagnostic, this error appeared

"Error: RosarioSIS cannot connect to the Postgres database. Either Postgres is not running, it was not started with the -i option, or connections from this host are not allowed in the pg_hba.conf file. Last Postgres Error:"

can i know in detail on how to start postgres database with the -i option using bitnami apps?

and if there is an easier method to install php and postgresql without using bitnami apps, may i know how?

**Comment by aarassen** [comment]
hello config.ini.php is the problem because is easy on windows hard on ubuntu
so try aggain and also you can find tuto in rosariosis but no for ubuntu so ihave the same problem but in ubuntu
