### ISSUE TITLE
LAPP stack

### ISSUE THREAD

**Issue by Isa1027** [francoisjacquet/rosariosis#230]
Good day!

Sorry, I can translate ROSARIOSIS into Spanish if I'm using LAPP stack.
This option is not the problem: https://github.com/francoisjacquet/rosariosis/blob/mobile/INSTALL.md

Thank you

**Comment by francoisjacquet** [comment]
Hello,

Good to know you were able to have RosarioSIS in Spanish.
Installation instructions are now also available in Spanish: https://github.com/francoisjacquet/rosariosis/blob/mobile/INSTALL_es.md
