### ISSUE TITLE
After sorting names alphabetically, grades are not saved in assignments 

### ISSUE THREAD

**Issue by abogadeer** [francoisjacquet/rosariosis#234]
Hi @francoisjacquet 

1- Create an assignment
2- Go to grades
3- Click on "Student" to sort the students by names alphabetically
4- Type in the grades and click save

The grades won't be saved
Click on Student again. 
Enter the grades and click save

The problem occurs when I change the sorting of students.

**Comment by francoisjacquet** [comment]
Hello @abogadeer 

Thank you for reporting this bug.

It happens when the category (first) filter is set to _All_, after sorting Students by name:
![image](https://user-images.githubusercontent.com/4723501/36378466-2e082e58-157b-11e8-9f96-e76e6a173274.png)

**Comment by abogadeer** [comment]
I also noticed strange behavior when I having a long list of students and trying to move the cursor using the "tab" key on the keyboard. _I think_ it moves according to the old sorting.
