### ISSUE TITLE
Changing schedule

### ISSUE THREAD

**Issue by abogadeer** [francoisjacquet/rosariosis#235]
Hi @francoisjacquet 

Yesterday, my school had to change the schedule in out school. We changed the courses' periods from being in the same period in every day to a different period in different days.

We did that for few courses. We faced several issues:

1- missing attendance data for past dates showed up, even though that teachers have taken attendance in those days.
2- The previous data seems to be deleted. Thanks god we had that on paper.
3- The process of changing was very time consuming. I suggest you show up something like the picture
![untitled](https://user-images.githubusercontent.com/29820341/36435132-e11dc876-1671-11e8-8d2c-ea5f136e689a.png)

**Comment by francoisjacquet** [comment]
Hello @abogadeer

Editing a course's periods after attendance has already been taken (same applies to grades in regard to course's marking period or grading scales) is not advisable.

In this case, you should:
1. Create a new course period reflecting your new school periods schedule.
2. Drop students from the old course period.
3. Add students to the new course period.

That way, you will be able to access old attendance data and no missing attendance warnings will show up.

This recommendation will be added to the [Helpful Tips for Administrators PDF](https://www.rosariosis.org/tips-did-you-knows/#administrator).

**Comment by abogadeer** [comment]
One more question:
If I do the steps mentioned above, what will happen to the grades and assignments' that I have given my students since I am going to drop students from the course period?

**Comment by francoisjacquet** [comment]
@abogadeer teachers will still access past grades and attendance for that Course Period.
