### ISSUE TITLE
Envió de correo y mensaje cuando el alumno registra una tardanza o inasistencia

### ISSUE THREAD

**Issue by netecperu** [francoisjacquet/rosariosis#237]
Buenas día y felicitaciones por el excelente proyecto.

Me gustaría saber si se puede incluir el envió de correo y mensajes a los padres cuando el alumno llega tarde o registra inasistencia.

Espero sus comentarios.

Saludos

**Comment by francoisjacquet** [comment]
Hello @netecperu 

Thank you for your good words.

Email notifications to parents when students are late or absent could be added to the [Email module](https://github.com/francoisjacquet/Email/).

If you wish to sponsor this enhancement, please contact us at https://www.rosariosis.org/services/

**Comment by francoisjacquet** [comment]
We have good news!

The [Email Parents module](https://www.rosariosis.org/email-parents-module/) can send Absence Notification to Parents.
