### ISSUE TITLE
problem change of language

### ISSUE THREAD

**Issue by chezmohamed** [francoisjacquet/rosariosis#238]
when i click on the france flag the language of change not even in spanish still remains in english
Someone can help me ?

**Comment by francoisjacquet** [comment]
Hello @chezmohamed 

This is surely a locale / PHP `gettext` issue.

Please search [related closed issues](https://github.com/francoisjacquet/rosariosis/issues?utf8=%E2%9C%93&q=is%3Aissue+language) before opening a new one.

**Comment by chezmohamed** [comment]
thanks
