### ISSUE TITLE
changing php version to 7.0 causes an error

### ISSUE THREAD

**Issue by abogadeer** [francoisjacquet/rosariosis#239]
Hi @francoisjacquet 
My school's site is hosted on a server with php 5.6. I changed the used version through cpanel to 7.0  and it had the following  notes (All files with the extension .php will be handled by the PHP 7.0 engine.
Latest version of PHP. all subdirectories will use ~/public_html/php.ini)

When I try to open Rosario, I get the following error:
Fatal error: Uncaught Error: Call to undefined function pg_connect() in /home2/daralulo/public_html/system/database.inc.php:55 Stack trace: #0 /home2/daralulo/public_html/system/database.inc.php(86): db_start() #1 /home2/daralulo/public_html/system/Warehouse.php(84): DBQuery('SET TIMEZONE TO...') #2 /home2/daralulo/public_html/system/index.php(13): require_once('/home2/daralulo...') #3 {main} thrown in /home2/daralulo/public_html/system/database.inc.php on line 55

This is the help page from webhost's site

https://my.bluehost.com/hosting/help/447

**Comment by francoisjacquet** [comment]
Hello @abogadeer 

The error simply indicates PHP is missing the `pgsql` extension.
It is not related to PHP7.

An issue related to PHP7 is to be found here: https://github.com/francoisjacquet/rosariosis/issues/163

Please contact your host or get support at https://www.rosariosis.org/services/
