### ISSUE TITLE
HOW TO INSTALL ROSARIO SIS ON WINDOWS

### ISSUE THREAD

**Issue by ZeroSplice** [francoisjacquet/rosariosis#24]
http://pastebin.com/BF7ccXSt

**Comment by benitoski** [comment]
Hi all
I just installed Rosario SIS on win 10 environment. Apache and php are provided by Xampp. I installed PostgreSQL also.
The thing is I can't get the locale ins in Spanish. I changed the config.inc.php lint to:
$RosarioLocales = array('es_ES.utf8') but the pages are still displayed in English.
Is there another setting elsewhere to change? Am I doing wrong something?
Thanks in advance
Oscar

**Comment by francoisjacquet** [comment]
Hi @benitoski 

You may experience issues with PHP > 5.4 and gettext (used for translations) on Windows. Please prefer this new tutorial: https://github.com/francoisjacquet/rosariosis/wiki/How-to-install-RosarioSIS-on-Windows

**Comment by benitoski** [comment]
Hi @francoisjacquet
I followed the install instructions you mention but I'm having a problem in the 'Import database' section.
When I run the sql I got a bunch of errors that make me think that something is wrong with the SQL database...

First attempt: 
       "#1193 - Unknown system variable 'client_encoding' "
When I comment "SET client_encoding = 'UTF8';" I get the following error 
       "#1193 - Unknown system variable 'check_function_bodies' "
When I comment "SET check_function_bodies = false;" I get the following error
       "#1193 - Unknown system variable 'client_min_messages' "
When I comment "SET client_min_messages = warning; " I get the following error:
        "#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS $$
    CREATE LANGUAGE plpgsql' at line 17 "

Despite having followed your instructions, all the above (and specially the last error) make me suspect that I don't have PostgreSQL but MySQL Is that possible?
On the Bitnami WAPP page there were just a single option to download:
![captura de pantalla 2015-10-15 19 37 41](https://cloud.githubusercontent.com/assets/7276118/10529451/75a53720-7374-11e5-9d24-3192ba4004f0.png)
And after install Bitnami WAPP the application looks:
![captura de pantalla 2015-10-15 19 44 34](https://cloud.githubusercontent.com/assets/7276118/10529547/310b6656-7375-11e5-98eb-929f27cf9c83.png)

What am I doing wrong?
Thanks in advance
Oscar

**Comment by francoisjacquet** [comment]
Hi @benitoski 

We can offer you support for RosarioSIS installation at http://www.rosariosis.org/services/

**Comment by jeetdebnath** [comment]
Hello Francoisjacquet
How to install rosariosis on linux hosting server using cpanel? after Installation it showing

Fatal error: Call to undefined function pg_escape_string() in /home/kidzagar/public_html/log/database.inc.php on line 258

**Comment by frendy13** [comment]
Hello Francois Jacques,

Congratulations for this project. Could you please confirm for me if I can use a MySQL database instead of the PostgreSQL one if I would use a migration tools. If Yes, in what files I must carry out some update?
