### ISSUE TITLE
No students found when creating report cards

### ISSUE THREAD

**Issue by abogadeer** [francoisjacquet/rosariosis#240]
hi @francoisjacquet 
Whenever I try to create report cards, I get the following message: 
No students were found. 

This happens to admin accounts and parents accounts
I checked their schedules and it seems everything is ok

I am using 3.8
PHP 5.6.34
postgresql ver 8.4 (I think) they removed the info from cpanel

**Comment by francoisjacquet** [comment]
Hello @abogadeer

Thank you for reporting this.

We will update the error message as it should read "No final grades were found for the selected students.".

**Comment by francoisjacquet** [comment]
The "No Final Grades were found" should now be displayed instead.
