### ISSUE TITLE
assignments of other teachers still appear to parents

### ISSUE THREAD

**Issue by abogadeer** [francoisjacquet/rosariosis#241]
Hi @francoisjacquet 
Several parents complained to me that assignments of other teachers who teach the same course but different periods still appear to them when they click assignments on their accounts.

I took the permission from one of them and checked for myself. 

The same applies to students accounts. There are home works of other teachers who teach the same course but different period

**Comment by francoisjacquet** [comment]
Hello @abogadeer

Thank you for reporting this bug.
I confirm assignments are wrongly showing up to students enrolled in another period of the same course in the _Assignments_ program.

This only happens when the _Apply to all periods of this course_ checkbox is checked.
