### ISSUE TITLE
Blank options / Checkboxes on Referal screen

### ISSUE THREAD

**Issue by Johan2018** [francoisjacquet/rosariosis#242]
Hi, I ran a diagnostic after installation and no errors were reported. However when I open the referral screen on the Disciplinary menu there are extra check boxes with no description next to them.

Rosariosis version 3.8
OS - Ubuntu 16.04
PHP -7
Postgressql 9.5

![rosario - add referral](https://user-images.githubusercontent.com/37780293/37878871-d7c0c586-306f-11e8-9913-9da7f49fa709.png)

Behaviour was the same with Firefox and Chrome.

**Comment by francoisjacquet** [comment]
Hello @Johan2018 

Thank you for the screenshot.

Those are probably extra spaces added during the `rosariosis.sql` file import.
Have you imported the database with phpPgAdmin? If yes, try again following those steps: https://github.com/francoisjacquet/rosariosis/wiki/How-to-install-RosarioSIS-on-Windows#import-the-database

Anyway, you can also remove those spaces by editing the _**Referral Form**_ fields.

Please tell us if it helps!

**Comment by Johan2018** [comment]
Fantastic! The copy of the sql as per the article did the trick.

Thank you very much.
