### ISSUE TITLE
error when try to get a database backup

### ISSUE THREAD

**Issue by abogadeer** [francoisjacquet/rosariosis#245]
Hi @francoisjacquet 
I get this error when I try to get a database backup
Error: The path to the database dump utility specified in the configuration file is wrong! (/public_html/system/backup/)
I created a folder called backup

I am using the latest build of Rosario
php 5.6.35
PostgreSQL 8.4
Chrome

What am I doing wrong?

**Comment by francoisjacquet** [comment]
Hello @abogadeer 

The `$pg_dumpPath` variable (see [`config.inc.sample.php`](https://github.com/francoisjacquet/rosariosis/blob/mobile/config.inc.sample.php#L37) file for examples) should point to your server's `pg_dump` binary / executable.

You probably do not have access to it if you are on shared hosting.
But they surely have some backup utility / facility you can use / setup from your control panel.

**Comment by abogadeer** [comment]
I will have to use ssh to get a database dump.



thanks
