### ISSUE TITLE
Absence summary issue

### ISSUE THREAD

**Issue by abogadeer** [francoisjacquet/rosariosis#246]
Hi @francoisjacquet 

I am suing the latest build
php 5.6 postgresql 8.4

1- login as admin
2- go to attendance
3- absence summary
4- choose all periods

you will get an error

Date: | 04/15/2018 01:51:22
-- | --
Failure Notice: | DB Execute Failed.
Additional Information: | ERROR: syntax error at or near ")" LINE 3: AND ap.PERIOD_ID IN () ^

**Comment by francoisjacquet** [comment]
Hello @abogadeer 

Thank you for reporting the issue.
The fix will ship with RosarioSIS 3.9
