### ISSUE TITLE
I cant Login using username admin and password admin after installing version 3.8

### ISSUE THREAD

**Issue by osborneomuya** [francoisjacquet/rosariosis#248]
1. Search [closed issues](https://github.com/francoisjacquet/rosariosis/issues?q=is%3Aissue+is%3Aclosed) first.

2. Specify your RosarioSIS, PHP & PostgreSQL **versions**, along with the server & browser used.

3. **Steps to reproduce** the problem.

4. Attach a **screenshot**.

**Comment by francoisjacquet** [comment]
Hello,


1. Have you searched [closed issues](https://github.com/francoisjacquet/rosariosis/issues?q=is%3Aissue+is%3Aclosed)?

2. Could you please specify your RosarioSIS, PHP & PostgreSQL **versions**, along with the server & browser used.

3. Could you please give **steps to reproduce** the problem?

4. And finally, attach a **screenshot**.

Thank you.
