### ISSUE TITLE
Add notification for outstanding school fees when users like parent login

### ISSUE THREAD

**Issue by adeseg** [francoisjacquet/rosariosis#249]
i would love if u can give me the code or process to add notification for school fess just like the food notification when parent login

**Comment by francoisjacquet** [comment]
Hello @adeseg

Thank you for your enhancement idea.

Either you can contribute your own code based on the Food Service portal alerts (maybe the Discipline Referrals notifications too?) in the `Portal.php` file, or you can sponsor the development.

Please check the https://www.rosariosis.org/contribute/ page for directions.

**Comment by francoisjacquet** [comment]
Hello @adeseg 

New Fee portal alert to Parents since version 5.4.
