### ISSUE TITLE
Suggestion : Print Receipt after receive payment

### ISSUE THREAD

**Issue by azwanmuslim** [francoisjacquet/rosariosis#25]
HI

Just want to request some features, can you please add some functions to print some kind of receipt after payment has been made?

Currently there are only option to print statements, but all transactions will be printed along, 

It would be great if user can print some kind of receipt, containing only the current payment that has been made, so that the receipt copy can be given to parents / student

Thanks

**Comment by francoisjacquet** [comment]
Hi @azwanmuslim,

We can offer you custom developments services  at http://rosariosis.org/services/

Thank you,
François

**Comment by francoisjacquet** [comment]
Good news!

The new **Student Billing Premium module** is available for download at  https://www.rosariosis.org/student-billing-premium-module/

It features the _Print Receipts_ program so you can generate and print PDF receipts.
It also adds a link for quick access on the _Payments_ program screen. 
Consult sample receipt PDF and preview the module (demo) [here](https://www.rosariosis.org/student-billing-premium-module/).
