### ISSUE TITLE
suggestion: Checked Course Period days should correspond to calendar weekdays

### ISSUE THREAD

**Issue by abogadeer** [francoisjacquet/rosariosis#251]
Hi @francoisjacquet 

When adding course period, the checked the days are always Monday to Friday

It would be great if the checked days correspond to the default days in calendar

In my case, our weekdays start from Sunday to Thursday. 

Making the days in the adding new course period corresponds to the calendar would make my life easier a lot.

Thanks

**Comment by francoisjacquet** [comment]
Hello @abogadeer 

I understand your point, but I am afraid there is no way to deduce which week days are school days from the Calendar as any day can be changed (from green to red) after creation.

**Comment by abogadeer** [comment]
@francoisjacquet 
Isn't there a way for me to change them manually in my own installation? So many mistakes were made last semester because of wrong days.

**Comment by francoisjacquet** [comment]
Closed for inactivity.
