### ISSUE TITLE
HTTP ERROR 500 

### ISSUE THREAD

**Issue by andresh0816** [francoisjacquet/rosariosis#253]
Hello, my problem is this. I don't know for what launch this error.

![image](https://user-images.githubusercontent.com/20376163/43437121-0d67804e-944d-11e8-8459-40e0db6baf78.png)
![image](https://user-images.githubusercontent.com/20376163/43437157-3341cc2a-944d-11e8-9d89-d258e9e9ad0d.png)

**Comment by francoisjacquet** [comment]
Hello,

For installation issues, you can buy email support at https://www.rosariosis.org/es/services/

Please also note that:

- the project has moved to Gitlab: https://gitlab.com/francoisjacquet/rosariosis/issues/
- you are trying to install RosarioSIS version 1, why?
- you are using WAPP stack 7.1 although version 5.4 is recommended in the Windows tutorial: https://gitlab.com/francoisjacquet/rosariosis/wikis/How-to-install-RosarioSIS-on-Windows

**Comment by andresh0816** [comment]
Regarding version 1 of rosarioSIS, which one should I use?
