### ISSUE TITLE
Http Error 500 this page isnt working on localhost

### ISSUE THREAD

**Issue by 167324** [francoisjacquet/rosariosis#254]
2. Specify your RosarioSIS, PHP & PostgreSQL **versions**, along with the server & browser used.
Rosario SIS 3.9.2
PHP 7.1.19
PostgreSql 9.2
Localhost Binami wamp
Google chrome

I typed in my 127.0.0.1/rosariosis and it says this pages isnt working http 500
Please help!!

**Comment by francoisjacquet** [comment]
Hello @167324 

Please refer to issue #253 and please [search closed issues](https://gitlab.com/francoisjacquet/rosariosis/issues?scope=all&utf8=%E2%9C%93&state=closed) before opening a new one.
