### ISSUE TITLE
Add different student Fields 

### ISSUE THREAD

**Issue by nadeemjamadar** [francoisjacquet/rosariosis#257]
As in india we dont need filelds like Etnicity and social securityno so want to make change in ADD STUDENT module

**Comment by francoisjacquet** [comment]
Hello @nadeemjamadar 

You can Delete or reuse the Ethnicity and Social Security fields by going to _Students > Student Fields > General Info_:
![image](https://user-images.githubusercontent.com/4723501/76142000-96705c00-6069-11ea-81b8-3291b48fdef6.png)


Also, please open issues at GitLab: https://gitlab.com/francoisjacquet/rosariosis/issues/

**Comment by nadeemjamadar** [comment]
![Capture123](https://user-images.githubusercontent.com/42204036/76144556-ad35a380-60a7-11ea-9069-ee5e0070aae6.PNG)

No fileds are displayed
