### ISSUE TITLE
DB Execute Failed - Adding User

### ISSUE THREAD

**Issue by ekowkoomson1** [francoisjacquet/rosariosis#258]
Hi Francois,

I have successfully installed Rosariosis on my ubuntu VPS but having challenges adding users.

Below is the error I get when I try to save.

03/25/2020 15:07:23
--
**_DB Execute Failed. ERROR: column s.phone does not exist LINE 3:_** **_...RNAME,s.PASSWORD,s.SCHOOLS,s.PROFILE,s.PROFILE_ID,s.PHONE,s.... ^Failure Notice_**_**

Please how do I resolve this?

Thanks.

Ekow.

**Comment by francoisjacquet** [comment]
Hello @ekowkoomson1 

You must have downloaded a development / beta version of RosarioSIS.
Please download RosarioSIS from the [Download](https://www.rosariosis.org/download/) page or a stable release from [GitLab](https://gitlab.com/francoisjacquet/rosariosis/-/tags/) and reinstall.

Also, please open issues at GitLab: https://gitlab.com/francoisjacquet/rosariosis/issues/

**Comment by ekowkoomson1** [comment]
Hi Francois,

Many thanks for your prompt response.

I followed your advice, downloaded and reinstalled Rosariosis using the stable version 5.8.1 (which happened to be the latest as of now) and it's working fine now.

Kindly noted. Will post future issues at the Gitlab url ( https://gitlab.com/francoisjacquet/rosariosis/issues/) you specified.

Thanks and remain BLESSED.
