### ISSUE TITLE
Responsible disclosure - Bug

### ISSUE THREAD

**Issue by M507** [francoisjacquet/rosariosis#260]
Hi @francoisjacquet

I want to report a vulnerability on RosarioSIS project. Can you please open a security advisory in the security section here on Github and add me to it, so we can discuss the vulnerability privately?

**Comment by francoisjacquet** [comment]
Hello @M507 

For this matter, you can open a private issue at GitLab: https://gitlab.com/francoisjacquet/rosariosis/-/issues

Thank you.

**Comment by M507** [comment]
Definitely!

**Comment by M507** [comment]
Thank you francoisjacquet. https://github.com/francoisjacquet/rosariosis/commit/9cb4fec5fe177f1d3716708b46d1958eac477ebe
