### ISSUE TITLE
ROSARIO SIS iomad

### ISSUE THREAD

**Issue by ken4ward** [francoisjacquet/rosariosis#261]
First, thanks to the creator of this project. it's a wonderful piece of relief to  people like me who wants to use IOMAD and ROSARIO SIS. I successfully integrated both based on the guideline in the documentation. The companies in IOMAD were pulled into ROSARIO SIS, which is what I want with a clause of an error popping up most times.

```
The error reads 
Note: Check The plugin configuration has been modified.
Warning Warning: A single company is associated to various schools.

X Error
Moodle: 23000021 - Access control exception | ERRORCODE: accessexception
Iomad: Could not get company category.
Moodle: 23000021 - Access control exception | ERRORCODE: accessexception
Iomad: Could not get company category.
```
Any suggestion of where the error could come from and how to fix it?

Second, it's not clear to me how the relationship will work. Want I want is to use IOMAD as the LMS while ROSARIO SIS as the SIS. I'd thought it'll create a course link for each student registered in a course in IOMAD so that all they need to do is click it and it'll redirect them IOMAD course page. 
Please, I need a clear guide on what the plugin is designed and developed to achieve.

Thanks. Hoping to hear from you.

**Comment by francoisjacquet** [comment]
Hello @ken4ward 

You will find more about the Moodle error here: https://duckduckgo.com/?q=moodle+access+control+exception&ia=web

Please post your solution.

Regarding what the Iomad plugin does, please check the [README](https://gitlab.com/francoisjacquet/Iomad/-/blob/master/README.md#description).
The plugin comes on top of the _Moodle_ plugin, here is the [README](https://gitlab.com/francoisjacquet/rosariosis/-/blob/mobile/plugins/Moodle/README.md#description).

Next time, please open your issue at [GitLab](https://gitlab.com/francoisjacquet/rosariosis/-/issues). GitHub is just a mirror.

**Comment by ken4ward** [comment]
Thanks @francoisjacquet this truly help in the right direction. It solved the problem I'd been trying to handle.
