### ISSUE TITLE
Standard documentation on theme creation

### ISSUE THREAD

**Issue by ken4ward** [francoisjacquet/rosariosis#262]
I've been trying to search for a theme creation documentation, someone should help lead me to the right direction. 
Thanks a lot.

**Comment by francoisjacquet** [comment]
Hello @ken4ward 

Please consult the [assets/themes/README.md](https://gitlab.com/francoisjacquet/rosariosis/-/blob/mobile/assets/themes/README.md)

Once again, please open your next issue or reopen this one at [**GitLab**](https://gitlab.com/francoisjacquet/rosariosis/-/issues), not GitHub.
