### ISSUE TITLE
Theme Background Change

### ISSUE THREAD

**Issue by WebDev22** [francoisjacquet/rosariosis#266]
Hello, 

I want to change the background of the WPadmin theme. The backgrounds of both the main window and the side menu and the bottom menu as well. I've tried to tinker around with the stylesheet.css files but it seems to be a mess to even decipher. Where can I change the colors to such things for RosarioSIS? 

Thanks

**Comment by francoisjacquet** [comment]
Hello @WebDev22 

You can start a new theme based on the [WPadmin theme icon sets](https://www.rosariosis.org/wpadmin-theme-icon-sets/)

Please remember to open your issues at [GitLab](https://gitlab.com/francoisjacquet/rosariosis/-/issues/), thank you.
