### ISSUE TITLE
Deleting student in mid quarter

### ISSUE THREAD

**Issue by frahman80** [francoisjacquet/rosariosis#267]
Hi,

How to delete a student in the middle of a quarter?

I’ve unenrolled all courses and set a drop date prior to enrollment. But I don’t see any delete option in the student info.

Rosario version  6.8.1 with moodle integration.

Thanks in advance.

**Comment by francoisjacquet** [comment]
Hello @frahman80

You can only delete a student who has no info / foreign keys related to him in the database.
But you can still drop it by selecting a Drop date from the _Student Info_ screen. The student will become inactive.
You will find more info in the [Helpful Tips PDF](https://www.rosariosis.org/tips-did-you-knows/#administrator).

Please remember to open your issues at [GitLab](https://gitlab.com/francoisjacquet/rosariosis/-/issues/) or ask questions on the [forum](https://www.rosariosis.org/forum/)
