### ISSUE TITLE
GetStuList.fnc.php format for USA phone number

### ISSUE THREAD

**Issue by dzungdo** [francoisjacquet/rosariosis#269]
File **./functions/GetStuList.fnc.php**, line 892:

`                                mb_substr( $phone, 3, 4 ) . '-' . mb_substr( $phone, 7 );`

Will return phone number as (123) 4567-890

I changed to:
`                                mb_substr( $phone, 3, 3 ) . '-' . mb_substr( $phone, 6 );`

Which will format correctly for phone number in the US as (123) 456-7890

**Comment by francoisjacquet** [comment]
Hello @dzungdo 

Thanks for the [fix](https://gitlab.com/francoisjacquet/rosariosis/-/commit/24e6c97d45b988bcc09fa8a6f23fa1b613b37a6a). It will come with RosarioSIS v7.3.

Please remember to open your issues at [GitLab](https://gitlab.com/francoisjacquet/rosariosis/-/issues)!
