### ISSUE TITLE
Search.fnc.php performs wrong query

### ISSUE THREAD

**Issue by dzungdo** [francoisjacquet/rosariosis#270]
Select: Menu > Users > Associate Students with Parents 
This bring up a search page,
One of the preconfigured field is "Email Address" - this searches correctly.

I have a custom field named "Phone", with type of "Text"

When search, the result failed to find anything. Because Search is searching for "custEmail"

**Comment by francoisjacquet** [comment]
Hello @dzungdo 

I was not able to reproduce the issue:
![image](https://user-images.githubusercontent.com/4723501/96768848-9cd7fc00-13de-11eb-883a-c8068f168de2.png)

![image](https://user-images.githubusercontent.com/4723501/96768896-a95c5480-13de-11eb-9092-2cd2d272ab0a.png)

![image](https://user-images.githubusercontent.com/4723501/96768924-b37e5300-13de-11eb-8edb-8a3568e1c766.png)

Please provide screenshots or a video which clearly shows the issue.

**Comment by dzungdo** [comment]
In my case, I can reproduce it every time. 

1. Select "Associate Students with Parents" 
![image](https://user-images.githubusercontent.com/8642776/96777609-874fdb80-13b8-11eb-9c6f-2008aa3e7427.png)

2. 
![image](https://user-images.githubusercontent.com/8642776/96777687-a189b980-13b8-11eb-973c-c60188fe99c3.png)

3. 
![image](https://user-images.githubusercontent.com/8642776/96777792-c54cff80-13b8-11eb-8eee-181d98ac7337.png)

4. 
![image](https://user-images.githubusercontent.com/8642776/96778001-09400480-13b9-11eb-8493-2a3fe68f1218.png)

I am using 7.2.2

**Comment by dzungdo** [comment]
Inspecting HTML codes on two different pages:

**Associate Parents with Students**
Student Email
```
<tr class="">
   <td><label for="custCUSTOM_200000015">Student Email</label></td>
   <td><input type="text" name="cust[CUSTOM_200000015]" id="custCUSTOM_200000015" size="24" maxlength="1000"></td>
</tr>
```

Student Mobile Number:
```
<tr class="">
   <td><label for="custCUSTOM_200000016">Student Mobile Number</label></td>
   <td><input type="text" name="cust[CUSTOM_200000016]" id="custCUSTOM_200000016" size="24" maxlength="1000"></td>
</tr>
```
					
**Associate Students with Parents**
User Email:
```
<tr class="">
   <td><label for="custEMAIL">Email Address</label></td>
   <td><input type="text" name="cust[EMAIL]" id="custEMAIL" size="24" maxlength="1000"></td>
</tr>
```

User Mobile Number: (This is a different custom field but same content)
```
<tr class="">
   <td><label for="custEMAIL">Mobile Number</label></td>
   <td><input type="text" name="cust[EMAIL]" id="custEMAIL" size="24" maxlength="1000"></td>
</tr>
```
Should `cust[EMAIL]` be something like `cust[CUSTOM_200000001]` ?

**Comment by francoisjacquet** [comment]
Hello @dzungdo 

Thank you for the screenshots.
The issue is fixed. Please upgrade to v7.2.3
