### ISSUE TITLE
Can this be used with MySQL since my host doesn't offer PostgreSQL?

### ISSUE THREAD

**Issue by TurboTronix** [francoisjacquet/rosariosis#271]
Was just wondering if there was a way to use this with MySQL...

**Comment by francoisjacquet** [comment]
Hello @TurboTronix 

Please check the Wiki, [No MySQL support](https://gitlab.com/francoisjacquet/rosariosis/-/wikis/No-MySQL-support) page.

**Comment by TurboTronix** [comment]
Ok thanks, guess it's time for me to change host. Can't wait to play with your code!
