### ISSUE TITLE
is this mirror of gitlab

### ISSUE THREAD

**Issue by zivian** [francoisjacquet/rosariosis#272]
@francoisjacquet is this mirror of gitlab? if yes, please update accordingly on github and gitlab.

**Comment by francoisjacquet** [comment]
Hello @zivian 

Yes, this is a GitLab mirror.
What do you mean by
> please update accordingly on github and gitlab

Is there a commit (this is automatic) or release (manually created by myself) missing on GitHub?

**Comment by zivian** [comment]
hello @francoisjacquet you can also modify your repo description similar to `Mirror of official Scribus SVN (however you should really use SVN at svn://scribus.net) (http://bugs.scribus.net ← Submit PRs & Bugs)` as on https://github.com/scribusproject/scribus

**Comment by francoisjacquet** [comment]
Hello @zivian 

This is what I had initially done (editing the GitHub repo description), but I think the [pinned issue](https://github.com/francoisjacquet/rosariosis/issues/252) is enough for this matter.
Thank you.
