### ISSUE TITLE
Tiny Formula Javascript error with formulat

### ISSUE THREAD

**Issue by DocStem** [francoisjacquet/rosariosis#277]
There is a warning error on the Tiny Screen for the javascript when you bring it up. It cannot find the reference. You can just close the popup error and continue if not using formulas.

**Comment by francoisjacquet** [comment]
Hello @DocStem 

Cannot reproduce the issue on Firefox on the demo site.
Please post a screenshot or a video showing the issue.

Please refer to #252 if you wish to reopen the issue.
