### ISSUE TITLE
What is the difference between this repository and the premium package?

### ISSUE THREAD

**Issue by curiosport** [francoisjacquet/rosariosis#278]
Is there a link comparing the features? I am not sure if the premium package is the same as this repository with the difference that you provide the hosting and support.

If I purchase the premium package from this link what do I get?
https://www.rosariosis.org/premium-bundle/

I get a zip file with the code? is self-hosted or what? what limits are there on the use of the code? For example if I can only use it on one computer or something like that. Or do I receive a hosting service?

**Comment by francoisjacquet** [comment]
Hello @curiosport 

The Premium Bundle contains:
- RosarioSIS (this same repository)
- Every free and Premium (paid) [add-ons](https://www.rosariosis.org/add-ons/)

in a single zip file.

So this is a convenient way to install RosarioSIS if you wish to get advantage of all the add-ons. The price is also reduced compared to buying Premium add-ons individually.

There is no use restriction or license code. Only free software.
Please note, this does not include hosting and support (for this, head to https://www.rosariosis.com/).

**Comment by curiosport** [comment]
@francoisjacquet wow that's pretty cool, and one question, what payment methods are available for parents who must pay the institution?

**Comment by francoisjacquet** [comment]
For now, only PayPal is available:
- https://www.rosariosis.org/plugins/paypal-registration/
- https://www.rosariosis.org/modules/student-billing-premium/

Let me know if you are interested in other payment gateways.

**Comment by curiosport** [comment]
@francoisjacquet Is there an option to for example send the payment invoice as a photo and then have the administrator manually review the invoice? In that case the administrator only reviews the deposit history in his bank account.

**Comment by francoisjacquet** [comment]
@curiosport has your question about the Premium bundle been answered?

The forum is better suited to ask questions about RosarioSIS use: https://www.rosariosis.org/forum/
(GitHub issues are best to report bugs)
