### ISSUE TITLE
Translation to Portuguese

### ISSUE THREAD

**Issue by francoisjacquet** [francoisjacquet/rosariosis#279]
Hello @pamellaneco @LorranyaN,

Would you be interested in translating RosarioSIS to Portuguese?

**Comment by emerson-pj** [comment]
Hello,
I'm interested. Brazil.

I'm available.
I have a friend who also understands English and other Spanish well and can help.
I am a programmer and he is a teacher.
We want to put RosarioSis in our institution.
It would be very interesting to put it in Brazilian Portuguese (RosarioSIS Premium bundle version).

Send me an email so I can answer you with our Institutional website that is already in 3 languages.
For you to know our technical translation work for teaching.
We are a Post-graduate Program (Master, PhD and Post-doctorate) with Brazilian and foreign students

**Comment by francoisjacquet** [comment]
Hello @emerson-pj 

Thank you for showing your interest.
You can send me an email (as shown on https://www.rosariosis.org) if you want to discuss private details.

**Comment by francoisjacquet** [comment]
Translation added to v10.9. Thank you @emerson-pj
