### ISSUE TITLE
Internationalization don't work

### ISSUE THREAD

**Issue by jrichardsz** [francoisjacquet/rosariosis#280]
I followed this https://gitlab.com/francoisjacquet/rosariosis/-/wikis/Localizing,-translate-RosarioSIS-with-Poedit#activating-your-translation-in-rosariosis trying to use Spanish as default language

![image](https://user-images.githubusercontent.com/3322836/211164925-ea17d185-9116-46ed-b366-78638c7804f5.png)

I restarted, and when I tried to login appeared the locale in the url

![image](https://user-images.githubusercontent.com/3322836/211164952-f2e8ff8c-ad56-4ab6-8534-24ff5a6ad0e5.png)

But after login, the entire login continues in english

![image](https://user-images.githubusercontent.com/3322836/211164878-bfcbbdf5-c905-41ae-b722-2ae38053789f.png)

Thanks

**Comment by francoisjacquet** [comment]
Windows
https://github.com/francoisjacquet/rosariosis/issues/107

Linux
https://github.com/francoisjacquet/rosariosis/issues/17

More help
https://www.rosariosis.org/services/

**Comment by carlosalaniz** [comment]
@jrichardsz Did you ever make it work?
