### ISSUE TITLE
French locale not working on Ubuntu 22.04

### ISSUE THREAD

**Issue by IchCodes** [francoisjacquet/rosariosis#288]
Hi all, hope you're doing well

I am writing to seek assistance with an issue I've encountered after the installation of **RosarioSIS**.

To provide some context, the installation process went smoothly, and everything seems to be working as expected. 
However, I have encountered a problem when attempting to change the **locale** to French. 
The issue is as follows:

When I change the locale to French, I can see the French flag on the interface, and the URL appears to change to reflect the locale.

https://XXXXX/index.php?locale=fr_FR.utf8

However, after logging in, the main RosarioSIS interface continues to display in English, with only a few fields appearing in French.

I have taken the following steps to diagnose and address the problem:

- Checked the diagnostic page at http://XXXXX/diagnostic.php. 
- According to the diagnostic page, my **RosarioSIS installation is properly configured**.
- Despite this, the issue with the incorrect display of locales persists. 
- I am unsure of how to proceed to resolve this matter.

Please advise me on how I can fix this language localization problem within RosarioSIS, ensuring that the application correctly displays in the selected locale (French, in this case).

**Comment by francoisjacquet** [comment]
Hello @IchCodes 

To install the locale, please follow the instructions in the[ INSTALL.md](https://gitlab.com/francoisjacquet/rosariosis/-/blob/mobile/INSTALL.md?ref_type=heads#other-languages) file.

**Comment by IchCodes** [comment]
> Hello @IchCodes
> 
> To install the locale, please follow the instructions in the[ INSTALL.md](https://gitlab.com/francoisjacquet/rosariosis/-/blob/mobile/INSTALL.md?ref_type=heads#other-languages) file.

I've already follow all the steps and language still not display in French

**Comment by IchCodes** [comment]
After the command sudo apt-get install language-pack-fr and a reboot it works, thanks for your support !
