### ISSUE TITLE
I found a security issue. 

### ISSUE THREAD

**Issue by manuel-sommer** [francoisjacquet/rosariosis#291]
Hi, 

could you please merge https://github.com/francoisjacquet/rosariosis/pull/290 as I found a security issue. 
I would like to submit it safely.

**Comment by manuel-sommer** [comment]
Please also enable "private vulnerability reporting":
![grafik](https://github.com/francoisjacquet/rosariosis/assets/47991713/52246f21-b324-4bbb-be1a-412bf4cec1c0)

**Comment by manuel-sommer** [comment]
I retested it, but I can't reproduce the issue. Still, you can enable the way to report safely a security recommendation

**Comment by francoisjacquet** [comment]
Hello @manuel-sommer 

Please read https://github.com/francoisjacquet/rosariosis/issues/252 and open issues at GitLab (you can open confidential issues there).
