### ISSUE TITLE
Errors Connecting to Moodle

### ISSUE THREAD

**Issue by SolutionsDEV** [francoisjacquet/rosariosis#292]
Good day,

I have installed IOMAD 4.1.4 & Rosariosis 11.3.2 which includes  Moodle integrator. I referred to the page at https://gitlab.com/francoisjacquet/rosariosis/-/wikis/Moodle-integrator-setup.

I have done all the steps in the Moodle integrator setup accurately as mentioned, when adding functionality as per section "3.7 Add functions", although there are many functions that may not be required like block related and big blue button related, anyway I added all of them.

Once finished in Moodle, it shows me in tokens page /admin/webservice/tokens.php that there are missing capabilities, I left them as they are, but will remove them if necessary.

On the other hand, after entering details in Moodle Integrator in Rosariosis and saving them, I am trying to test is using test button, but it shows a red error on top of the page that says "AJAX error. 503 Service Unavailable. //site/rosariosis-v11.3.2/Modules.php?modname=School_Setup/Configuration.php&tab=plugins&modfunc=config&plugin=Moodle&save=true", the same error shows if I try to configure IOMAD plugin in Rosariosis.

What do I need to do to make it run?

Thanks a lot,

![Rosariosis-Moodle-01](https://github.com/francoisjacquet/rosariosis/assets/17509158/183d0578-99d7-4bf7-9d23-d0d7ee267cbb)
![Rosariosis-Moodle-02](https://github.com/francoisjacquet/rosariosis/assets/17509158/40a4cc29-202e-47eb-83e8-409b8e6a06d3)

**Comment by francoisjacquet** [comment]
Hello @SolutionsDEV 

Thank you for the screenshots.

A 503 Service Unavailable means "The server cannot handle the request (because it is overloaded or down for maintenance). Generally, this is a temporary state."
But apparently this is misleading here.

Do you have php-curl extension installed?
What does the //site/rosariosis-v11.3.2/diagnostic.php page read?
What does the Apache `error.log` read?

Do you have the same error on the [demo](https://www.rosariosis.org/demo/)?

**Comment by SolutionsDEV** [comment]
Hello @francoisjacquet,

Thanks for your quick reply.

The server does not have any issues, it is actually a local VPS so it is fast and does not have any issues. Yes, curl is installed and running for all PHP versions including PHP7.4 which I am currently running this implementation on it.

For the diagnostic page it replies with "Your RosarioSIS installation is properly configured."

For the other suggestions, I will check the error logs, for the demo, I cannot configure it as with the local VPS it is not accessible from outside the network.

By the way, I have set many schools within this implementation, does it make any issues?

I will get back to you with the error log details.

Regards,

**Comment by SolutionsDEV** [comment]
Hi @francoisjacquet,

I did not look at the logs, but rather tried to test it on completely another platform. It seems that because the initial setup was on local machine and it was not internet accessible, although it is accessible in URL this caused the issue.

I installed Rosariosis and copied Iomad on an internet server that is internet accessible so everything worked fine without any issues. I modified the role in Iomad to enable connection to Rosariosis as per https://www.rosariosis.org/plugins/iomad/.

Although the connection was fine, but in the Iomad plugin configuration in Rosariosis, it did not show a selection of the company and did not provide the ability to create a new school. 

Trying to know the issue cause, I used and set up the demo at https://www.rosariosis.org/demonstration, but it also did not provide anything as per the screenshot, then I removed setting from the demo.

Any suggestions?

Thanks a lot,

![Rosariosis-Moodle-03](https://github.com/francoisjacquet/rosariosis/assets/17509158/7f7d97d4-f71f-4346-8db6-d180a5bdd0e3)

**Comment by francoisjacquet** [comment]
Hello @SolutionsDEV 

Good to know you were able to fix the issue.

About Iomad companies:
![image](https://github.com/francoisjacquet/rosariosis/assets/4723501/01d49849-2ca6-4e4b-97be-0e4db902cceb)
The dropdown does indeed show an empty option below the "N/A" option...

Anyway, the additional setup for Iomad is detailed here https://www.rosariosis.org/plugins/iomad/

And the WS function to get companies is `block_iomad_company_admin_get_companies`.

Without any error, no more can be stated.

**Comment by SolutionsDEV** [comment]
Hello @francoisjacquet,

I have added the remaining functions, now I can see and select it, I will continue exploring and setting. 

What invokes synchronization? 

I guess I have seem somewhere about demo data to be imported into Rosariosis; would you guide me where?

Thanks a lot for you help,

Regards,

**Comment by francoisjacquet** [comment]
Hello @SolutionsDEV 

Good to know you were able to complete the Iomad integration.

You will find the points of integration in the Moodle plugin's [README.md](https://gitlab.com/francoisjacquet/rosariosis/-/blob/mobile/plugins/Moodle/README.md)

**Comment by SolutionsDEV** [comment]
@francoisjacquet Thanks again, I read the readme file, but could not find the details I want about:

What invokes synchronization? Does it need to set a cron?

I guess I have seem somewhere about demo data to be imported into Rosariosis; would you guide me where?

Regards,

**Comment by francoisjacquet** [comment]
Hello @SolutionsDEV 

> What invokes synchronization? Does it need to set a cron?

No

> I guess I have seem somewhere about demo data to be imported into Rosariosis

There is no demo data.
