### ISSUE TITLE
forgot password

### ISSUE THREAD

**Issue by bleedingmie** [francoisjacquet/rosariosis#295]
hi i randomly got logged out of my admin account and i forgot the password, how can i reset it?
I didn't add an email along my account

**Comment by francoisjacquet** [comment]
Hello @bleedingmie 

First, please read https://github.com/francoisjacquet/rosariosis/issues/252

To reset your password, please click on the "Password help" link on the login screen, then enter your email address.

This will work if
- RosarioSIS can send email
- You have set an email address for your admin user

**Comment by bleedingmie** [comment]
i don't have an email linked to my admin user

**Comment by francoisjacquet** [comment]
Then you will either have to set one, or reset the password hash in the `staff` table using phpMyAdmin / phpPgAdmin / Adminer.

Here is the default password (`admin`) hash: 
```
$6$dc51290a001671c6$97VSmw.Qu9sL6vpctFh62/YIbbR6b3DstJJxPXal2OndrtFszsxmVhdQaV2mJvb6Z38sPACXqDDQ7/uquwadd.
```
