### ISSUE TITLE
Custom field for multi-row entries (table-like structure) 

### ISSUE THREAD

**Issue by biosmooth** [francoisjacquet/rosariosis#41]
Hi,

I tried to find custom field which will enable presenting data consisting of multiple rows. Something like table with few columns (e.g. Id, Name, Title, Date) and more than one row. 
I did not manage to customize available custom fields (multiple selection types, long type) to do so.
I think brand new custom field would be the best option. I am eager to help with the development of this feature. Could You please give me some details where to begin my journey with this task :) ? Maybe some useful hints or URLs  containing basic information useful for new developer (e.g. turning on debug mode, etc. )  ?

**Comment by francoisjacquet** [comment]
The **long text** custom field type now supports [Markdown (wiki)](https://github.com/francoisjacquet/rosariosis/wiki/Markdown-Cheatsheet#tables).
You can for example store and display tables (rows & columns) (see _MDTextarea_ field below):
![screenshot from 2016-05-17 15 26 52](https://cloud.githubusercontent.com/assets/4723501/15338053/d708f77c-1c43-11e6-91a9-70557db66e3d.png)
