### ISSUE TITLE
Student Class requests

### ISSUE THREAD

**Issue by anthonycastro8** [francoisjacquet/rosariosis#42]
Is there a way where students can add there own class requests instead of having the admin doing it for them? It saves admins a lot of time if they do it this way.

**Comment by ghost** [comment]
i had same request there is any modules to do that

**Comment by francoisjacquet** [comment]
Hello @anthonycastro8 , @keko00 & @glassofmilk13

Thank you for sharing your enhancement idea.

Students (and parents) currently have _read_ access to the **Student Requests** program.

If you would like to sponsor the development so Students can _edit_ their Requests, please contact us at https://www.rosariosis.org/services/

**Comment by francoisjacquet** [comment]
The **Student Requests** program is now accessible to Students (or their Parents), see commit c89e467e3331147e80faf651f650821c98027d4c. You can give them _Edit_ access in the _User Profiles_ program.


Please upgrade first to [version 3.2](https://github.com/francoisjacquet/rosariosis/releases).
