### ISSUE TITLE
Custom fields in the letters

### ISSUE THREAD

**Issue by wasimfadloun** [francoisjacquet/rosariosis#46]
Hello ,

is there a way to use custom fields in the 'Print Letter' ?

**Comment by francoisjacquet** [comment]
Hello,

No it is not possible as is and would require a custom development.

François

**Comment by francoisjacquet** [comment]
Custom fields (_text_, _select_ and _date_ types) could be added as a new substitution:
`__CUSTOM1__`: [fields dropdown]

This could be the opportunity to create a `ProgramFunctions/Substitutions.fnc.php` file to regroup the code for substitutions used in various programs.
