### ISSUE TITLE
WKHTMLTOPDF didn't return any data

### ISSUE THREAD

**Issue by Samuelseggs** [francoisjacquet/rosariosis#47]
when i try to print a page i get this error WKHTMLTOPDF didn't return any data on ubuntu 14.04

**Comment by francoisjacquet** [comment]
@Samuelseggs
Importing students to RosarioSIS from CSV is a service I can offer you. 
Please see http://www.rosariosis.org/services/ for more details and 
contact info.

François Jacquet

**Comment by francoisjacquet** [comment]
Hello,

This is clearly a font problem.

You may need to install the missing font packages if you run RosarioSIS 
on Linux:
See for example this issue:
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1646

Please note that this is a wkhtmltopdf issue, see 
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/

François

**Comment by francoisjacquet** [comment]
@daedumo,

 From what I can see on your screenshot, the teacher inquestion does not 
have any course period associated (see the blank drop-down list in the 
left menu).
As the teacher can only see the students in his courses periods, it is 
normal behaviour.

The Github issues are for reporting bugs or error.
Si necesita soporte por email, por favor contácteme en la página 
http://www.rosariosis.org/es/services/

François Jacquet

**Comment by francoisjacquet** [comment]
Maybe you could try 'C:/Progra~1/wkhtmltopdf/bin/wkhtmltopdf.exe'

**Comment by ErikSmart** [comment]
For the problem for WKHTMLTOPDF didn’t return any data, Is it is because you do not have installed WKHTMLTOPD. In this blog show how install wkhtmltopdf in ubuntu 14 32 bits http://powerericc.tumblr.com/post/127578923241/como-instalar-en-ubuntu-14041-wkhtmltopdf-32

**Comment by francoisjacquet** [comment]
A related issue where the **PDF would never finish loading on Windows** was reported on the forum: [Help.php not keeps loading and cannot access rosariosis system](https://www.rosariosis.org/forum/d/3-help-php-not-keeps-loading-and-cannot-access-rosariosis-system)

It has been fixed in version 3.3.1.
