### ISSUE TITLE
Input Final Grades - Rosario

### ISSUE THREAD

**Issue by LeoRAS** [francoisjacquet/rosariosis#50]
Goodmorning Francois,

I have a version of Rosario on paid Webhosting.
When I clicked Input Final Grade (as Teacher or Admin), I encountered the following error:

We have a problem, please contact technical support...

Date:   07/15/2014 09:38:26

Failure Notice:      DB Execute Failed. 

Additional Information:     ERROR: function credit(integer, unknown) does not exist LINE 1: ...ITLE as COURSE_NAME, cp.TITLE, cp.GRADE_SCALE_ID, credit(2, ... ^ HINT: No function matches the given name and argument types. You might need to add explicit type casts.

This issue has been posted before, but was apparently discontinued by the opener. On basis of your response I checked the page source, however I cannot find the  Web developer --> Page Source ?

I have another version on WAMP server where this problem does not occur.

Thank you.

**Comment by kbjaoui** [comment]
Hi Francois,

I am having exactly the same error.


We have a problem, please contact technical support ...
Date:	
09/20/2017 03:48:24
Failure Notice:	
DB Execute Failed.
Additional Information:	ERREUR: la relation � config � n'existe pas LINE 2: FROM CONFIG ^


SQL STATEMENT: 

SELECT TITLE, CONFIG_VALUE
			FROM CONFIG
			WHERE SCHOOL_ID='0'



Thank you.

**Comment by francoisjacquet** [comment]
Hello @kbjaoui 

What does the _diagnostic.php_ page tell? https://github.com/francoisjacquet/rosariosis/blob/mobile/INSTALL.md#installation-problems
