### ISSUE TITLE
Adding picture to portal note throws warnings

### ISSUE THREAD

**Issue by ghost** [francoisjacquet/rosariosis#56]
Adding picture to portal note throws following warnings:
Warning: finfo_file(): Failed identify data 0:(null) in /home/xxx/public_html/ProgramFunctions/PortalPollsNotes.fnc.php on line 340
Warning: finfo_file(): Failed identify data 0:(null) in /home/xxx/public_html/ProgramFunctions/PortalPollsNotes.fnc.php on line 346

RosarioSIS 2.5.6
Php: 5.4.3

**Comment by JuanPonce** [comment]
Hola termine de instalar el programa RosarioSis, pero no logro cambiarle el idioma a Español. Que me falto hacer?
