### ISSUE TITLE
ERROR: permission denied for sequence staff_seq

### ISSUE THREAD

**Issue by patrickubong** [francoisjacquet/rosariosis#72]
Hi, thanks for your usual prompt response. The Rosariosis is working perfectly except when I try to add a new record like: a new school, a new user or any new record at all and I get:
Date: 09/29/2014 10:14:26
Failure Notice: DB Execute Failed. 
Additional Information: ERROR: permission denied for sequence schools_seq

Date: 09/29/2014 10:24:52
Failure Notice: DB Execute Failed. 
Additional Information: ERROR: permission denied for sequence staff_seq

**Comment by kevinleeTCA** [comment]
Since PostgreSQL 8.2 you have to use:

GRANT USAGE, SELECT ON SEQUENCE cities_id_seq TO www;
GRANT USAGE - For sequences, this privilege allows the use of the currval and nextval functions.
