### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by mnjenga** [francoisjacquet/rosariosis#77]
1) Is it Possible to give parents access to the discipline module to see associated student's records
2) In Accounts/ Student Billing to remove the delete entry option and replace it with option to correct with a negative posting for audit purpose 
3) Create option to generate user log/ changes done by any user

**Comment by francoisjacquet** [comment]
1) Done, see below
2) see answer to 3)
3) you now have the Access log program. But a full user log could be an enhancement. If you are interested, please contact us 
at http://rosariosis.org/services/

**Comment by francoisjacquet** [comment]
Good news, the Parents & Students can now have access to the Discipline Referrals. ([check the v2.8.26 release](https://github.com/francoisjacquet/rosariosis/releases))
To enable it, go to _Users > User Profiles_ and check _Can Use Referrals_.

Cheers
