### ISSUE TITLE
getting error "Call to undefined function bindtextdomain() in apache\www\rosariosis\Warehouse.php on line 47"

### ISSUE THREAD

**Issue by rukunpuc** [francoisjacquet/rosariosis#85]
PostgreSQL v 9.3.5
apache v 2.4
PHP v 5.5.17

After after performing all the initial tasks and importing rosariosis.sql file , I was getting a blank screen when accessing the directory from url. After putting the following lines: 

ini_set('display_errors', '1');
error_reporting(E_ALL | E_STRICT);

The page is now showing error "Call to undefined function bindtextdomain() in C:\Program Files (x86)\PostgreSQL\EnterpriseDB-ApachePHP\apache\www\rosariosis\Warehouse.php on line 47"

Would you please help me regarding this?

**Comment by francoisjacquet** [comment]
Your PHP installation probably miss the gettext extension as the 
function bindtextdomain() is provided by it.
I will add the gettext extension check in diagnostic.php file so it is 
easier to spot.

**Comment by rukunpuc** [comment]
Hi!

Thank you for your reply. I have added php_gettext.dll file in PHP files
directory and enabled the gettext extension from php.ini. But still the
problem has not been solved.

Please help me in this regard.

Best Regards,
Sheikh Md Rukunuddin Osmani

**Comment by francoisjacquet** [comment]
What does the diagnostic.php script say?

**Comment by rukunpuc** [comment]
It is also showing a blank screen if I just go to diagnostic.php from url

Please help me regarding this issue.

**Comment by francoisjacquet** [comment]
This is not normal.
You have a problem with your PHP configuration, but I do not know what 
it could be.
Have you tried other PHP scripts, do they present problems too?

**Comment by francoisjacquet** [comment]
A new [tutorial for Windows](https://github.com/francoisjacquet/rosariosis/wiki/How-to-install-RosarioSIS-on-Windows) is available.
The translations have been successfully tested!

Cheers

**Comment by francoisjacquet** [comment]
Since version 3.8 (March 2018), RosarioSIS counts with `gettext`, `mbstring`, `json` & `xml` **emulation** (shim, polyfill, see `functions/PHPCompatibility.php`).
If one of those PHP extension is not installed, RosarioSIS will therefore continue working relying on those soft emulated alternatives.
It is still recommended to install proper extensions as they offer more speed and reliability.
