### ISSUE TITLE
Error when searching for a student as administrator

### ISSUE THREAD

**Issue by lrcarlisle** [francoisjacquet/rosariosis#92]
Since updating to 2.7 I receive the error "more than one row returned by a subquery used as an expression".  This happens when I search for a student (searching for an user does NOT return this error).  Also, this ONLY occurs when I'm signed in as the administrator.  When I sign in as an user it works fine.  Any ideas?

**Comment by francoisjacquet** [comment]
Thank you for reporting the error.

In order to investigate, I would need the SQL statement in question.
It is present in the Rosario Database error email you should have 
received, or inspecting the code in the browser, after <!-- SQL statement
(via right click > Inspect element)

**Comment by lrcarlisle** [comment]
Is this what you need?

**Comment by francoisjacquet** [comment]
You have not posted anything...

**Comment by lrcarlisle** [comment]
I'm sorry.  I copied and pasted it but then it disappears from the post.  I'm new to this.

**Comment by francoisjacquet** [comment]
SELECT s.LAST_NAME||', '||s.FIRST_NAME||' '||coalesce(s.MIDDLE_NAME,' ') AS FULL_NAME,(SELECT sch.TITLE FROM SCHOOLS sch WHERE ssm.SCHOOL_ID=sch.ID) AS SCHOOL_TITLE,s.LAST_NAME,s.FIRST_NAME,s.MIDDLE_NAME,s.STUDENT_ID,ssm.SCHOOL_ID,ssm.GRADE_ID  FROM STUDENTS s JOIN STUDENT_ENROLLMENT ssm ON (ssm.STUDENT_ID=s.STUDENT_ID AND ssm.SYEAR='2014' AND ('13-JAN-2015'>=ssm.START_DATE AND (ssm.END_DATE IS NULL OR '13-JAN-2015'<=ssm.END_DATE)) AND ssm.SCHOOL_ID='2') WHERE TRUE  AND LOWER(s.LAST_NAME) LIKE 'acosta%'  ORDER BY s.LAST_NAME,s.FIRST_NAME,s.MIDDLE_NAME

**Comment by francoisjacquet** [comment]
I am not able to reproduce the error.
So maybe you could help me:
If you replace the line 196 in the _functions/GetStuList.fnc.php_ file with this one:
<pre>
$sql .= '(SELECT sch.TITLE FROM SCHOOLS sch WHERE ssm.SCHOOL_ID=sch.ID LIMIT 1) AS SCHOOL_TITLE,';
</pre>

Do you still have the error?

**Comment by lrcarlisle** [comment]
Yes, I still have the error.

**Comment by lrcarlisle** [comment]
If no one else has experienced this error then I imagine it is a local problem for me.  Could it have anything to do with the rollover?  Looking at the database tables I see the staff are all listed twice: for 2014 and 2015 with the id numbers being changed.  Not so with the students.  They are just listed once and with the same custom id number we gave them in 2014.

**Comment by francoisjacquet** [comment]
I have experienced the same error after the rollover, indeed.
Changing the line 196 in the _functions/GetStuList.fnc.php_ file with this one:
<pre>
$sql .= "(SELECT sch.TITLE FROM SCHOOLS sch WHERE ssm.SCHOOL_ID=sch.ID AND sch.SYEAR='".UserSyear()."') AS SCHOOL_TITLE,";
</pre>
Fixed the problem for me.
Could you confirm it is OK too on your side please?
I will then release the fix.

**Comment by lrcarlisle** [comment]
Yes, it appears to have fixed it.  Thanks!!!

On Tue, Jan 13, 2015 at 9:40 PM, François Jacquet <notifications@github.com>
wrote:

> Closed #92 <https://github.com/francoisjacquet/rosariosis/issues/92> via
> 513f9b1
> <https://github.com/francoisjacquet/rosariosis/commit/513f9b16edd4622acf286012d750b0287afd4885>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/francoisjacquet/rosariosis/issues/92#event-218454373>.
>



-- 
Larry R. Carlisle
*http://www.carlislefamily.net <http://www.carlislefamily.net>*

**Comment by francoisjacquet** [comment]
Thank you for helping me improve RosarioSIS.
