### ISSUE TITLE
Moodle Integration not Working?

### ISSUE THREAD

**Issue by JohnGWS** [francoisjacquet/rosariosis#93]
Hi
I have installed Rosario 2.7 and Moodle 2.8.2 and they are both working normally. I went through the Moodle Integration steps carefully and all seemed to be in order, but I do not have any detectable integration. I have tried adding users in Rosario to see if they show up in Moodle, and vice versa, and nothing changes. What am I missing?
Thanks
John

**Comment by francoisjacquet** [comment]
Hi John,
please contact me via http://www.rosariosis.org/services/ if you need help to configure the Moodle integrator.
François
