### ISSUE TITLE
Session data

### ISSUE THREAD

**Issue by kwesidev** [francoisjacquet/rosariosis#94]
Why is that session data isn't stored in a database ??

**Comment by francoisjacquet** [comment]
Why not?

**Comment by kwesidev** [comment]
because storing them in a database will be much safer..

**Comment by francoisjacquet** [comment]
I would prefer not to enter in a debate whether it is safer to compare the IP and User Agent of the client against their values stored in DB. Anyway, the User Agent can be modified easily and the IP spoofed.

I have followed the recommendations on this page http://php.net/manual/en/session.security.php and applied the measures that could be applied in Warehouse.php, see https://github.com/francoisjacquet/rosariosis/commit/cfddc731ffea531c2f4fe3c67db19615d45c7ac1

I have updated the wiki too: https://github.com/francoisjacquet/rosariosis/wiki/Secure-RosarioSIS
