### ISSUE TITLE
Can't find new student

### ISSUE THREAD

**Issue by lrcarlisle** [francoisjacquet/rosariosis#95]
I have version 2.7 installed.  Just a few days ago I added two new students and assigned them to their classes.  Today when I tried to locate them, the program says the no student is found.  I tried entering their information again but it says the RosarioID that I had assigned them is taken.  So in essence, the RosarioID was saved but evidently without any student information.  Any idea what caused this and what can be done now?  I just now installed 2.8beta4 hoping that would fix it but it doesn't.  Any help would be appreciated.  Thanks.

**Comment by francoisjacquet** [comment]
Do the students in question appear if you check "Include Inactive Students"?

**Comment by lrcarlisle** [comment]
Yes, they do.  Being in the southern hemisphere, we are just beginning the
school year in a few days.  The students who were enrolled last year appear
in the search but the ones just recently enrolled do not because, I assume,
we have not started the school year yet.  Thanks for the tip.

On Mon, Feb 23, 2015 at 6:26 PM, François Jacquet <notifications@github.com>
wrote:

> Do the students in question appear if you check "Include Inactive
> Students"?
>
> On 02/23/2015 02:36 PM, lrcarlisle wrote:
> >
> > I have version 2.7 installed. Just a few days ago I added two new
> > students and assigned them to their classes. Today when I tried to
> > locate them, the program says the no student is found. I tried
> > entering their information again but it says the RosarioID that I had
> > assigned them is taken. So in essence, the RosarioID was saved but
> > evidently without any student information. Any idea what caused this
> > and what can be done now? I just now installed 2.8beta4 hoping that
> > would fix it but it doesn't. Any help would be appreciated. Thanks.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/francoisjacquet/rosariosis/issues/95>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/francoisjacquet/rosariosis/issues/95#issuecomment-75624634>
> .
>



-- 
Larry R. Carlisle
*http://www.carlislefamily.net <http://www.carlislefamily.net>*

**Comment by lrcarlisle** [comment]
Has anyone else had problems in signing in with 2.8 beta 4?  I installed it last night to try to fix the previously mentioned issue and was able to sign in afterwards; but today everytime I enter the username and password, the program signs me in and then out immediately.  That is, I see the regular screen after signing in but then it returns to the login screen.  Is it a problem that others have reported with beta 4 or just with my setup?

**Comment by francoisjacquet** [comment]
I have added some session hijacking prevention code so the session ID is 
regenerated every 3 minutes. Maybe your problem is related to that.

I was able to reproduce the problem with /session.auto_start/ set to *1* 
in the /php.ini/ configuration file: it logs out after 3 minutes of 
inactivity.

Could you please post the /session/ part of your server's /php.ini/ file?

**Comment by lrcarlisle** [comment]
Directive	Local Value	Master Value
session.auto_start	Off	Off
session.cache_expire	180	180
session.cache_limiter	nocache	nocache
session.cookie_domain	no value	no value
session.cookie_httponly	Off	Off
session.cookie_lifetime	0	0
session.cookie_path	/	/
session.cookie_secure	Off	Off
session.entropy_file	no value	no value
session.entropy_length	0	0
session.gc_divisor	1000	1000
session.gc_maxlifetime	1440	1440
session.gc_probability	1	1
session.hash_bits_per_character	5	5
session.hash_function	0	0
session.name	PHPSESSID	PHPSESSID
session.referer_check	no value	no value
session.save_handler	files	files
session.save_path	/tmp	/tmp
session.serialize_handler	php	php
session.upload_progress.cleanup	On	On
session.upload_progress.enabled	On	On
session.upload_progress.freq	1%	1%
session.upload_progress.min_freq	1	1
session.upload_progress.name	PHP_SESSION_UPLOAD_PROGRESS	PHP_SESSION_UPLOAD_PROGRESS
session.upload_progress.prefix	upload_progress_	upload_progress_
session.use_cookies	On	On
session.use_only_cookies	Off	Off
session.use_strict_mode	Off	Off
session.use_trans_sid	0	0

**Comment by francoisjacquet** [comment]
Alright, thanks to your PHP session config values, I discarded the 
configuration problem:
I have set my /php.ini/ session values identically to yours and there is 
no problem on my side.

Maybe you have changed the cookies management settings of your browser 
recently?
Have you tried with another browser?

**Comment by lrcarlisle** [comment]
Ok, then it must be on my install. I've tried on two different computers
and a tablet and get the same results. I used the same browser on all three
devices, though. I'll try another browser just to see. Is it possible for
me to revert back to 2.7 for now?

Thanks for looking into the configuration possibility.

**Comment by lrcarlisle** [comment]
Sometimes now it is allowing me to login but as soon as I press any menu
option on the left, it exits.  I've tried 3 or 4 different menu options and
it always exits the program.

On Tue, Feb 24, 2015 at 9:19 PM, Larry Carlisle <larry@carlislefamily.net>
wrote:

> Ok, then it must be on my install. I've tried on two different computers
> and a tablet and get the same results. I used the same browser on all three
> devices, though. I'll try another browser just to see. Is it possible for
> me to revert back to 2.7 for now?
>
> Thanks for looking into the configuration possibility.
>  On Feb 24, 2015 8:33 PM, "François Jacquet" <notifications@github.com>
> wrote:
>
>> Alright, thanks to your PHP session config values, I discarded the
>> configuration problem:
>> I have set my /php.ini/ session values identically to yours and there is
>> no problem on my side.
>>
>> Maybe you have changed the cookies management settings of your browser
>> recently?
>> Have you tried with another browser?
>>
>> On 02/24/2015 04:14 PM, lrcarlisle wrote:
>> >
>> > Directive Local Value Master Value
>> > session.auto_start Off Off
>> > session.cache_expire 180 180
>> > session.cache_limiter nocache nocache
>> > session.cookie_domain no value no value
>> > session.cookie_httponly Off Off
>> > session.cookie_lifetime 0 0
>> > session.cookie_path / /
>> > session.cookie_secure Off Off
>> > session.entropy_file no value no value
>> > session.entropy_length 0 0
>> > session.gc_divisor 1000 1000
>> > session.gc_maxlifetime 1440 1440
>> > session.gc_probability 1 1
>> > session.hash_bits_per_character 5 5
>> > session.hash_function 0 0
>> > session.name PHPSESSID PHPSESSID
>> > session.referer_check no value no value
>> > session.save_handler files files
>> > session.save_path /tmp /tmp
>> > session.serialize_handler php php
>> > session.upload_progress.cleanup On On
>> > session.upload_progress.enabled On On
>> > session.upload_progress.freq 1% 1%
>> > session.upload_progress.min_freq 1 1
>> > session.upload_progress.name PHP_SESSION_UPLOAD_PROGRESS
>> > PHP_SESSION_UPLOAD_PROGRESS
>> > session.upload_progress.prefix upload_progress_ upload_progress_
>> > session.use_cookies On On
>> > session.use_only_cookies Off Off
>> > session.use_strict_mode Off Off
>> > session.use_trans_sid 0 0
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/francoisjacquet/rosariosis/issues/95#issuecomment-75847370
>> >.
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/francoisjacquet/rosariosis/issues/95#issuecomment-75861756>
>> .
>>
>


-- 
Larry R. Carlisle
*http://www.carlislefamily.net <http://www.carlislefamily.net>*

**Comment by francoisjacquet** [comment]
Thank you for reporting the problem, I have created a separated issue for it and proposed a patch, see #96

**Comment by lrcarlisle** [comment]
I applied the patch but there is no change.  It still exits the program as
soon as I click on any part of the menu.

On Wed, Feb 25, 2015 at 12:40 PM, François Jacquet <notifications@github.com
> wrote:

> Thank you for reporting the problem, I have created a separated issue for
> it and proposed a patch, see #96
> <https://github.com/francoisjacquet/rosariosis/issues/96>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/francoisjacquet/rosariosis/issues/95#issuecomment-75970506>
> .
>



-- 
Larry R. Carlisle
*http://www.carlislefamily.net <http://www.carlislefamily.net>*
