### ISSUE TITLE
History making periods is not working correctly

### ISSUE THREAD

**Issue by peepslog** [francoisjacquet/rosariosis#98]
Hi,

Please can you help me to figure out how to use the history marking periods correctly?
Whenever I select a student to add or edit the history marking periods, it simply shows the current school year (2014-2015) but updates the grade level while I might have selected the history marking period of (2013-2014) which i previously created using the history marking periods settings.

Thanks

**Comment by francoisjacquet** [comment]
Hi @peepslog 

Please reserve the issues to report bugs or errors.
If you need support for RosarioSIS use, please visit http://rosariosis.org/services/
