### ISSUE TITLE
Cookie check

### ISSUE THREAD

**Issue by InsidiousMiss** [francoisjacquet/rosariosis#99]
After upgrading to 2.8.3, I can't stay logged in anymore. With the cookie check, it tells me I must have cookies enabled to use Rosario, but my cookies are enabled.

**Comment by francoisjacquet** [comment]
Thank you reporting the problem, and sorry for that.
Please upgrade to [2.8.4](https://github.com/francoisjacquet/rosariosis/releases), this version contains the fix.
However, if you check the _diagnostic.php_ page, I guess it will tell you have _session.auto_start_ activated, right?
Well, this is a potential security hole and should be addressed.
